### ISSUE TITLE
Adding attachment download access rights

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#101]
For the attachments, a restriction of the download rights is required. Currently every one who can read the document, can also download all attachments. But for "internal sources" or proprietary binaries maybe restrictions are required:

|  | contributor | moderator | creator | user | clearing admin | admin |
| --- | --- | --- | --- | --- | --- | --- |
| download OSS sources | R | R | R | R | R | R |
| download internal sources | R | R | R | - | - | R |

Let's check if there more attachments which would benefit from restrictions.

**Comment by mcjaeger** [comment]
there is hope for a pull request that solves this in some way ...

**Comment by maximilianhuber** [comment]
@mcjaeger is this solved by #375?

**Comment by mcjaeger** [comment]
This issue was moved to eclipse/sw360#6
