### ISSUE TITLE
The Footer and some About Box

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#107]
Origin: For testing and information the following information should be 
1. Commit tag
2. Branch name
3. Compilation timestamp.

This is very useful for testing and build / deployment control as also proven in the Fossology.

Currently the footer section is kind of wired. Links and e-mails are broken. so in the ideal case:

sw360 (version, build) | Copyright w/o link | Pop Up for Privacy with Content | Support with E-Mail configurable in sw360.properties.

**Comment by maximilianhuber** [comment]
That is a great idea.

Since partial builds are very common we have to find a good policy to decide which "build" was done. Maybe update this field with every (partial) build and not only with a build of the full project?

I would also suggest to add an timestamp of the build to the footer.

**Comment by mcjaeger** [comment]
(from discussion)
* let's have an about box
* let's use the plain http text response for each service ("Welcome to the sw360 fossology service!") to return version information (and maybe other runtime information, such as JRE info) in fact.
