### ISSUE TITLE
reuse of document detailed view in moderation request view

### ISSUE THREAD

**Issue by stefanjaeger-evo** [sw360/sw360portal#113]
the detailed view of the moderation requests for at least projects and components should reference the original `detailed.jsp` of the corresponding portlet.
already implemented for moderation requests of licenses.

**Comment by mcjaeger** [comment]
discussion: it is about code duplication, line 58 ff in https://github.com/sw360/sw360portal/blob/master/frontend/sw360-portlet/src/main/webapp/html/moderation/projects/merge.jsp

(affects components, releases, ... please check, not licenses as written above)

**Comment by mcjaeger** [comment]
(from discussion) projects is there, but releases for example not.
