### ISSUE TITLE
moderation request zombie

### ISSUE THREAD

**Issue by stefanjaeger-evo** [sw360/sw360portal#114]
if the last moderator of a moderation request clicks "remove me from moderators" the moderator will be removed. in this case the moderation request still exists in the database and cannot be accepted or declined by another moderator.

solutions can be:
* the button "remove me from moderator" will be disabled (including tooltip) or hidden
* the moderation request will be declined with or without notice

**Comment by maximilianhuber** [comment]
The first suggested solution introduces race conditions.

The second solution also might indroduce wrong behaviour and unwanted declines.

other possible solutions

- there are some roles / users / groups / ... which can not remove them self as moderator / are moderator of all moderation requests or
- (**better**) reject the "remove me..." request in the backend and show the user a popup which says: "you are the last, you can't remove yourself."
