### ISSUE TITLE
css improvements and refactoring for view JSPs

### ISSUE THREAD

**Issue by stefanjaeger-evo** [sw360/sw360portal#117]
out if the pull request #98 :

> @maximilianhuber commented on frontend/sw360-portlet/src/main/webapp/html/admin/bulkReleaseEdit/view.jsp in 1c09f15
> 
> I think it is a good idea to avoid mixing a relative width with a absolute padding. It can lead to different behaviour depending of the width of the container (i.e. scrollbars).
> 
> @maximilianhuber commented on frontend/sw360-portlet/src/main/webapp/html/admin/bulkReleaseEdit/view.jsp in 1c09f15
> 
> I think the searchInput occurs in many files and could be worth to move into its on .jspf-file. (In the medium run. Please create an issue if you decide to postpone it.)
> EDIT: or maybe add it as tag.

**Comment by mcjaeger** [comment]
(from discssion): first point:  issue to unspecific, second point solved
