### ISSUE TITLE
Write moderation request as diff to database

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#118]
At the moment, a moderation request (MR) contains the entire document - the document as it is in the db at the moment the MR is created -with the changes applied that the user wants to make. 

When a moderator evaluates the moderation request, the document in the db might have been changed in the meantime. In this case, the difference between the db-document and the document from the moderation request is misleading:

- changes that the requesting user wanted to make disappear if the same changes have already been made to the db-document.
- fields or attachments that the user did not want to change may appear as changes if the fields or attachments have changed in the db-document. They are changed back if the moderation request is accepted.
-Especially, the moderator does not know whether the user wanted to delete the attachment or if it just has been added to the db-document after the moderation request was created.

Quick and dirty solution: moderation requests can only be accepted if the revision hash at the document in the MR equals the revision hash of the db-document.

Better solution: change the way MR's are written to the database. Instead of saving the entire document, save only the fields that have been changed with the new value. For attachments maintain two lists: the new attachments with all attachment meta data and a list of deleted attachments. The latter needs only to contain the attachmentContentId of the attachments to delete.

**Comment by maximilianhuber** [comment]
I would suggest to introduce a new thing called `ModerationRequest<F>` which looks for Projects like
```java
ModerationRequest<Project>  mr = ModerationRequest<Project> {
    // metadata
    requester: "requester@sw360.org",
    requestDate: "2016-03-15",
    // ...
    // data
    toAdd: Project {
        title: "some new title",
        attachmants: ["some attachmant id"]
        //everything else is unset
    },
    toRemove: Project {
        title: "the old title",
        attachmants: ["another attachmant id"]
        //everything else is unset
    }
}
```
wich would result in a recipe which says:
* add the attachmant `"some attachmant id"`
* remove the attachmant `"another attachmant id"`
* change the title to `"some new title"` **only if** the title is `"the old title"`

That would (hopefully) be generic enough to be used for all moderation requests.

**Comment by mcjaeger** [comment]
what would be the plan here for this pull request to add this only for attachments for the first and then, as a second step, refactor this to the other moderation requests?  (fine with me)

**Comment by heydenreich** [comment]
No. There is already another PR that solves the _acute_ problem of broken moderation requests with attachments. (PR 120)

This issue is about rewriting _all_ moderation requests (with attachments or not) such that the precise changes of the requesting users are saved in the toAdd and the toRemove.

**Comment by heydenreich** [comment]
The Moderation Request is a thrift-struct. As far as I know, thrift does not support generics. At the moment, a moderation request is modeled as
```
struct ModerationRequest{
...
    20: optional Component component,
    21: optional Release Release,
    22: optional Project project,
    23: optional License license,
... 
}
```

We could replace this by:
```
struct ModerationRequest{
...
    20: optional Component componentAdd,
    21: optional Release ReleaseAdd,
    22: optional Project projectAdd,
    23: optional License licenseAdd,
    30: optional Component componentRemove,
    31: optional Release ReleaseRemove,
    32: optional Project projectRemove,
    33: optional License licenseRemove,
... 

}
```

**Comment by heydenreich** [comment]
Also deleting attachments from the sw360_attachments database should be done on decline and on deletion of a moderation request. Once we know, which attachments have actually  been uploaded for the moderation request at hand, this should be no problem any more.
