### ISSUE TITLE
unset project responsible/lead architect

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#119]
Once the lead architect or project responsible for a project is set, it is not possible to unset it. Changing to a different user is possible. Unset is possible for moderators - it should also be possible for lead architect and project responsible.

**Comment by mcjaeger** [comment]
just add button to clear

**Comment by mcjaeger** [comment]
(from discussion) while the project responsible might be kind of mandatory (just search the right one), this is a general issue for the single user input fields (also in components or releases) that use a radio button selection in the user search view. Once one user has been selected in this listing, there is now way to unset the radio button entirely. There should be a delete or unset option.
