### ISSUE TITLE
IE11: component Subscribe/Unsubscribe results in 'error' label

### ISSUE THREAD

**Issue by stefanjaeger-evo** [sw360/sw360portal#123]
steps to reproduce:
1. login as user@sw360.org
2. Click on a component name
3. Click on Subscribe, the label changes to “error” instead of Unsubscribe
4. Refresh the page, the label is Unsubscribe
5. Click on Unsubscribe, the label changes to “error” instead of Subscribe
6. Refresh the page, the label is Subscribe

**Comment by mcjaeger** [comment]
please contribute fix if you find this should find its way in master
