### ISSUE TITLE
admins role separation SW360 vs. Liferay

### ISSUE THREAD

**Issue by stefanjaeger-evo** [sw360/sw360portal#125]
for a clearer role separation between the sw360 admin and the liferay(setup) admin the following implementations are required:
- all liferay activities and setup right/roles should be transferred to liferay(setup) admin
- overview of users should list sw360 roles and liferay roles in separate columns
- the liferay admin should also be added to the wiki page containing the sw360 roles model

**Comment by maximilianhuber** [comment]
I think that for security reasons the setup admin was deleted. After your suggested changes this would delete the only liferay admin.

Is there a place, other than placing portlets, where the liferay admin functionality is needed (after a complete setup).

**Comment by mcjaeger** [comment]
discussion: sw360 admins should not move portlets anymore (so the controls are not hiding other UI elements). The portlet modification ting should be only visible to setup user (for liferay)

note that approving and rejecting  self-registration users should be tested. (maybe it works for the organization administrator (if the organisation is sw360...))

**Comment by maximilianhuber** [comment]
If a user is not Liferay-admin, he is not able to promote someone to ecc-admin or clearing-admin. This maybe could be solved by adding a custom "sw360-admin" with permissions to promote to some roles.

**Comment by maximilianhuber** [comment]
Closed by https://github.com/sw360/sw360portal/pull/404
