### ISSUE TITLE
Stay in edit mode after update component

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#130]
After updating a (new) component, users usually want to go on editing, e.g. adding releases etc.
Therefore, after updating the component, the edit mode of the component should be displayed.

**Comment by heydenreich** [comment]
I suggest that we do is the same as with releases: after adding a new component, stay in edit mode, after updating an existing one, go to the details view of that component.

If you stay in edit mode after updating, feedback about updating (e.g. "updated successfully" or "moderation request sent") is immediately overwritten by the information about the document state that is usually displayed when you enter the edit mode.

**Comment by mcjaeger** [comment]
please consider the same also for adding a project.
