### ISSUE TITLE
CPE ID not editable / Search for CPE at NIST

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#136]
The user shall be able to edit the CPE Id.

Please note that this works at creation of the release. However, it does not work in the edit mask (which looks super same).

At the same time, the system should show a search box, similar to vendor or user search, that could search the CPE from the NIST Web service. Then, among the existing (returned) ones, a CPE could be selected. Otherwise the user can assign an own value.

**Comment by bufferoverflow** [comment]
Please consider to use the [public service](https://cve.circl.lu/) based on [cve-search](https://github.com/cve-search/cve-search), it provides a simple [Web API](https://github.com/cve-search/cve-search#web-api-interface) and can also be installed on site (make the URL configurable).

**Comment by mcjaeger** [comment]
editable is there, please test

**Comment by mcjaeger** [comment]
editable works
remaining is to external service or set an autogenerated CPE (from vendor, component, version)

**Comment by mcjaeger** [comment]
should be clarified which service to call.

**Comment by mcjaeger** [comment]
This issue was moved to eclipse/sw360#11
