### ISSUE TITLE
Sticky filter for projects by Organisation

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#147]
When reviewing projects, in most cases a user likes to see "own projects". It is good that other projects are visible. However, when reviewing clearing status (the numbers) other projects are confusing. Currently, there is a filter for groups (confusingsly called "business unit"), however, that must be filled out manually, and then, also set every time again, the projects list view is called. Therefore:

* make a menue of all group values to select
* rename occurrences of business unit with "group", in the UI mabye org group if that  is less confusing.

**Comment by mcjaeger** [comment]
discussion: please not only cover session but for reoccurring logins

**Comment by mcjaeger** [comment]
discussed in group: custom fields in the user data object maintained by liferay for storing information about a user. Note that e-mail notification was a backend issue, while this appears a front end issue

**Comment by alex-evo** [comment]
So what should the businessUnit field be called in the UI? "Group"? "Org Group"? Something else? I find "Group" too generic.
I think in DB we're stuck with businessUnit.

**Comment by mcjaeger** [comment]
"group" should be fine

**Comment by mcjaeger** [comment]
tested with current master -> does not seem to work

**Comment by mcjaeger** [comment]
my fault: it was for group only. Works.
