### ISSUE TITLE
Used Projects in Components not easy to read for many projects

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#150]
For a long list of projects in the component view, the listing of projects should be row-wise, because for a longer listing with popular components, the listing of projects in a "single line" is not easy to read.

At least carriage return should be possible. As possible enhancements, the department and the project responsible could be named.

**Comment by mcjaeger** [comment]
suggestion - if access rights allow - also department and responsible could be displayed

**Comment by heydenreich** [comment]
I guess it is welcome to do the same for releases and projects (which could be used by other projects) as well.
