### ISSUE TITLE
Checksum field for attachments is too small

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#151]
Somehow, the screen layout can be easily set into a mode where the checksum is truncatedly displayed. It would be good to have the complete checksum in most cases - for super small screens of course not, but checksum is truncated at fixed width, regardless of the screen width (for example, truncated at 1920 width) (tested with IE11)

**Comment by mcjaeger** [comment]
is also in Firefox (truncated always) please change also display as plain text (like label style) and not input test field

**Comment by maximilianhuber** [comment]
The simple change `input` -> `span` introduces some ugliness when the browser width is very small but might be acceptable:

![tmp](https://cloud.githubusercontent.com/assets/1187050/18121318/47604dae-6f64-11e6-9ba8-f32747002ced.png)

**Comment by maximilianhuber** [comment]
By using `word-break: break-all;` one is able to obtain the following more pleasing behaviour:
![tmp](https://cloud.githubusercontent.com/assets/1187050/18121978/7d6766e6-6f67-11e6-8815-e03d40306f0b.png)
