### ISSUE TITLE
Attachment content is removed on update

### ISSUE THREAD

**Issue by alex-evo** [sw360/sw360portal#154]
Attachment content is deleted from sw360attachments when the attachment object is updated.
Steps to reproduce:
1. add an attachment to a release (project or component will work the same) and save it.  You can download the attachment content by clicking on the download link.
2. go to release edit page again and change the attachment's comment.
3. Save the release. Now you can't download the attachment content anymore. The response from server is empty if you click on download link.

Reason: `AttachmentConnector.deleteAttachementDifference` uses `Sets.difference` on  `Attachment` Sets, which considers the `Attachment` objects with the same `contentId` but different `comment`s as not equal. The "old" attachment content then gets deleted, although the reference to is still persists in the "new" attachment

**Comment by AngelM1981** [comment]
Ah this it is. It happened to me too. I wondered why the attachment download for some stuff does not work.
