### ISSUE TITLE
Delete confirmation dialog

### ISSUE THREAD

**Issue by timowolf** [sw360/sw360portal#156]
I just accidentally deleted a project. Of course it is my fault, but there was no delete confirmation or warning. Would be nice to have a delete confirmation.

**Comment by mcjaeger** [comment]
adding this that all deletions should be "to be confirmed".

**Comment by AngelM1981** [comment]
I can confirm this. It happened to me too.

Michael <notifications@github.com> schrieb am Mo., 2. Mai 2016, 12:26:

**Comment by mcjaeger** [comment]
suggestion: do not delete projects if releases are there.

**Comment by pfaffelmoser** [comment]
Apart from adding a confirmation dialogue after deleting projects etc. via the edit page, should there be a restriction with respect to linked releases (for projects)? If yes, there might be at least two options:
* do not allow deletion (similar to restriction for used projects)
* show warning ("there are linked releases") within confirm dialogue

**Comment by mcjaeger** [comment]
(from discussion)
list at warning text (if available):
* for projects, number of: linked releases, linked projects and attachments
* for components (deletion in case of linked not possible anyways), number of: attachments
* for releases, number of: linked releases, attachments.

**Comment by heydenreich** [comment]
We have now some special effect: if you click on the trash bin for a component you have to confirm that you want to delete the component although there is a release. If you click ok, the component (and release) cannot successfully be deleted. Reason is that the release is used in a project.

Solution: 
1) disable trashbin in that case?
2) add information about using projects to confirmation dialog?
