### ISSUE TITLE
Search for any user name return no user

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#169]
When trying to search for any user name, e.g. under Project -> User Information fields or under Component > Releases, even if the exact user name is entered in search dialog (e.g. Test User1), the message "No user found with your search." is displayed. When pressing Search button with empty string, the same user name can be seen is available in the list.

**Comment by mcjaeger** [comment]
requires retesting

**Comment by adrian-evo** [comment]
Fixed lately.
