### ISSUE TITLE
Some users assigned under private project can see the name of the project listed on home page

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#170]
Although Private projects names should not be seen by anyone else than the creator, users assigned as Lead Architect, Moderators or Contributors can see names of private projects on Home page under My Projects. Users assigned as Project responsible cannot see private projects which is as expected.

However, only name of private project is listed, when the user tries to open the project, the project is not available.

**Comment by mcjaeger** [comment]
it is within tolerable versions.
