### ISSUE TITLE
Name Search filter for components not working as expected

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#173]
When trying to use Name Search filtering on Component page, the returned result either is filtering both component name and vendor name, either is displaying components without filtered name, e.g.
- Adding "Comp" under Name search will return components with the name e.g. WinPCap, Apache Axis 2 and so on, none of them containing Comp in the name.
- Searching for "Test", returned a component with Test in the name as well as with Test under Vendor name.

**Comment by mcjaeger** [comment]
retest in group looks Ok now
