### ISSUE TITLE
Date field validates date format differently or not at all

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#174]
Under Project -> Admin information, any random numerical string can be entered instead of date, while letters are not allowed.
Under Release Date, any 4 digit number is accepted as valid date, while e.g. 3 digit number is not allowed.

**Comment by mcjaeger** [comment]
even 3 digit number works.

**Comment by mcjaeger** [comment]
I think we have still some problem because any value can be added see screnshot ...

![screen shot 2017-05-17 at 15 56 58](https://cloud.githubusercontent.com/assets/3418977/26157454/8c8f153c-3b19-11e7-9983-a42e506d3b40.png)
