### ISSUE TITLE
Linked releases - clearing status is also important

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#177]
For linked releases the clearing status is also important to see.

Situation: some creates a component with release. Then the release has linked releases. The clearing status of these linked releases should be visible to in the linked releases view (one of the menu items on the left side of the releases detail view).

Then, the maintainer of a component/release has an overview about the involved sub releases.

**Comment by maximilianhuber** [comment]
There are currently two possible views where linked releases are displayed:

- **Linked Releases And Projects** (is also the clearing status of the linked projects important?)
- **Linked Releases Hierachy** (might be mergeable with the tab Clearing Status)

**Comment by mcjaeger** [comment]
(requires discussion): actually, does it make sense that clearing status is OK but for sub releases not? also adding sub releases poses questions here to clearing status of release...

**Comment by mcjaeger** [comment]
(from discussion): 1) actually it is about the releases-subreleases page, not the linked releases of a project or other project portlet views. There is a simple table (which could be update to jquey tables as in other views) where the clearing status would be helpful. 2) displayed field would be field 17: clearingState

**Comment by heydenreich** [comment]
@mcjaeger @alex-evo : Did you realize that the table in question is a treetable. You can combine treetable with DataTable - I just tried it, but the result is probably not what you want:
1. The search of the DataTable finds only sub-releases if they are actually visible, i.e. if all ancestor-releases are expanded. If you start with a table, where nothing is expanded, the search will not find a sub-release.
2. The sorting of the DataTable mixes all visible releases, i.e. the child releases are not displayed under the correct parent release any more.
3. If search and sorting are not useful - why use datatable at all?

--> Shall I stick to the plain treetable?

**Comment by heydenreich** [comment]
This is how the combination treetable datatable looks like (_child_ -releases are _subreleases_ of _parent_, not of _some other release_.)
![image](https://cloud.githubusercontent.com/assets/14327740/18949618/7c3d7ada-863c-11e6-9f18-1082188468d9.png)

**Comment by heydenreich** [comment]
@mcjaeger @alex-evo Paging and treetables has also some special effects ;-)

**Comment by mcjaeger** [comment]
OK, understood, as we discussed, let's keep to display the information then.
