### ISSUE TITLE
Project Service can call Copyright and License Info service to aggregate CLIs

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#182]
#Goal is to have an aggregated text file for the 

* copyrights
* licenses

of all involved releases, where involved is about the releases of a project and the releases of the linked subprojects.

Text file listing could be separated by release name (e.g. Apache Tomcat 7.0.54).

User can click a button in the linked project tree view to generate this text file.

**Comment by alex-evo** [comment]
Can you please provide a template for the generated file?
