### ISSUE TITLE
License Service Edit Improvements

### ISSUE THREAD

**Issue by bs-jokri** [sw360/sw360portal#184]
1. Create sub pages for 
   - License Type
   - Risk Category
   - Obligations
   
   with "list all" and "detail" view
   
   with "add" and "edit" functionality
2. Rename tab "Risk" to "Risk and Risk Categories"
3. Add tab "Add a risk" to "License" detail view similiar to "Add a Todo"
4. Move edit of "external link" currently in License details view to edit mode of license
### Permissions

All users are allowed to view Licenses, Obligations, Risk Category, License Type

Admin is allowed to view and edit Licenses, Obligations, Risk Category, License Type

Clearing Admin is allowed to view and edit Licenses, Obligations, Risk Category, License Type
### Moderation Requests

Users can issue moderation requests for new Risks similar to Todos

**Comment by mcjaeger** [comment]
I recommend to completely engineer the license service (with obligations)

**Comment by mcjaeger** [comment]
This issue was moved to eclipse/sw360#16
