### ISSUE TITLE
Potentially Insecure Password Comparison in Signup Portlet

### ISSUE THREAD

**Issue by alex-evo** [sw360/sw360portal#185]
As discovered in the discussion of #183 (hat tip to @maximilianhuber), com.siemens.sw360.portal.portlets.signup.Reqistrant.java contains this ugly and potentially insecure snippet of code:

```
        try {
            SW360Assert.assertEquals(password, password2);
        } catch (SW360Exception e) {
            SessionMessages.add(request, "request_processed", "Passwords don't match");
            return false;
        }
```

Ugly, because an exception is used for control flow where an if statement is sufficient.
Potentially insecure, because `SW360Assert.assertEquals` may at any time add logging of the actual compared values and compromise user's password.

**Comment by maximilianhuber** [comment]
Solved (a long time ago)
