### ISSUE TITLE
Rename labels in release detail view

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#189]
Rename 1:  "Licenses" in the attributes of releases sounds misleading, because there should be many licenses, as found in the clearing report. However, this is not helpful here, because the information that people looks for is what the general component  (release, I know) main license is. rename -> "Main Licenses"
Rename 2: "Release Date" -> "Release Date of this Release"
Rename 3: "Contacts" is like very questionable, because the user cannot see what is it for. Could be renamed in "Contact person in org" or better provide a mouse over "i" information. (similar to existing "i" mouseovers)
Rename 4: Provide also in "i" mouse over info why to set the mainline status or what the values mean (OPEN: new, MAINLINE: recommended use, SPECIFIC: tolerated use, PHASE OUT: avoid use)

Additionally in Release Clearing details (both edit and normal view):
* process start and evaluation date -> rename to "evaluation start" and "Evaluation end"
* and change the order of the fields (field start before/left field for finish)
* put request id and request add info together in a separate box "Request Info": (Request Id, Evaluation end, Additional Request, evaluation start )
* put all ECC fields together see #191 under topic "ECC Info": (AL, ECCN, Material Index Number, Assessor Contact Person, Assessor Department, ECC Comment)

**Comment by alex-evo** [comment]
Rename 1 has already been done.

Rename 3: Contacts have been renamed to Contributors by #100. Is it necessary to add a mouseover hint now? If yes, what should it say?
