### ISSUE TITLE
Refactor Main Licenses in Components and Releases

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#19]
(original ticket from Johannes) 

Components and Releases have two fields:
* optional set<string> mainLicenseIds, 
* optional set<string> mainLicenseNames,

The Component fields are filled from Releases on Release change.

The names are never read, and set apart from the ComponentImporter.

The display of licenses is done via the DisplayLicense Tag, which looks up the whole license with the license client via the Id.

This is inconsistent and redundant and a solution would be to refactor licenses such that their Ids are the short names (so that the short names have to be unique, which they should anyway be). Then the two fields can be aggregated into one field.

The price would be that one can not easily change the shortname of a license after referencing it, but this rarely happens. Also it is easy to keep synchronous with fossology because there the license Id is the shortname.

**Comment by mcjaeger** [comment]
shaortname example: GPL-2.0 see identifier at: http://spdx.org/licenses/

big issue is that couchdb Ids are assigned at creation of the dataset, if the data set is re.created (at re provisioning of the DB with a new installation) the ids will be different.

**Comment by alex-evo** [comment]
Isn't it true, that it is also possible to get rid of mainLicenseNames fields by making component importer load license names on demand like DisplayLicense tag does? It seems to me this approach would require fewer changes as it would leave the license ids untouched. Am I missing something?
