### ISSUE TITLE
Clearing Status of projects

### ISSUE THREAD

**Issue by timowolf** [sw360/sw360portal#197]
In the clearing status view of a project, I see the status for each linked release. But I do not see the clearing status of the sub-dependencies of those. 

It would be great if the view has a button for also displaying the clearing status of the sub linked releases.

**Comment by mcjaeger** [comment]
Would it solve this ticket if we add clearing status as a column to this view?
![036 oss sw360 20160920 screenshot linked releases screenshot](https://cloud.githubusercontent.com/assets/3418977/18663213/d90adcba-7f1d-11e6-86e2-6dfdfc29e554.png)

**Comment by timowolf** [comment]
Yes, this view is great.

**Comment by heydenreich** [comment]
We already solved this issue recently
