### ISSUE TITLE
Not possible to select the changes to be accepted/declined from multiple moderation requests

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#198]
When multiple changes are proposed, e.g. changes in basic fields, adding linked releases and attachments, these are sent as only one moderation request, thus it is only possible to accept or decline them all and at once. Maybe it should be possible to select the changes to be accepted / declined?

**Comment by mcjaeger** [comment]
maybe it would be confusing for the moderation request submitter that would require evaluation how the moderation request was resolved (so it is creating a moderation request for a moderation request...?)
