### ISSUE TITLE
List Components with Main License

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#20]
Based on issue #19, a main use case asked for is to list components in the component main view by their main license (e.g. show only components with Apache-2.0 as main license)

At the same time, please limit the description to one line and truncate with three dots after a couple of chars (maybe 32?) and display full text with Mouse over.

At the same time, please change the default row view number from 10 to 25.

**Comment by mcjaeger** [comment]
let's remove description in favor of this field in the list of components

**Comment by alex-evo** [comment]
@mcjaeger, just to make sure I understand you correctly: does "list components by their main license" mean a new search filter on the left?
If yes, should it have autocompletion and should it search by license shortname or fullname, or both?

**Comment by mcjaeger** [comment]
Hi, I think the basic first ideas to have this as table column - then adding a filter on the left is OK (sounds like the straight forward solution)
