### ISSUE TITLE
Duplicate names of projects and components can be added

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#203]
Maybe this will create confusion if several users would be able to add projects or components with the same name?

**Comment by mcjaeger** [comment]
Well, for projects it should be possible to have two projects with the same name but different version. So the ticket would be not to allow for duplicate components
* release with same version
* component with same name
* project with same name AND version
* License with same short name
It should just no be possible to create them

**Comment by heydenreich** [comment]
The release name is not per se equal to the component name (maybe it should?) Therefore it should in my opinion also be:

* release with same name AND version

**Comment by heydenreich** [comment]
For licenses this is already solved since we have the id equal to the shortname.

**Comment by heydenreich** [comment]
Should a project w.r.t. name and version be unique across SW360? Or only within group?

**Comment by mcjaeger** [comment]
the entire sw360, because it could be otherwise dependent on visibility level - for public projects it is then applying, for private not and how do you deal with changes in visibility level. I vote for all sw360 unique.
