### ISSUE TITLE
Newly created projects, components and releases are not shown in search result

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#204]
When a user is creating some new projects (e.g. Proj 01, 02), or components and releases (e.g. Comp 01, 02), and tries to search for e.g. "Proj" or "Comp" as keywords, with or without Type selection, search results returns 0 entries.

**Comment by mcjaeger** [comment]
just tested in discussion: right now it seems to work.

**Comment by adrian-evo** [comment]
Tested and seems to work. Maybe the limit of showing 25 entries only will exclude some items from the search?

**Comment by mcjaeger** [comment]
OK, solved by now
