### ISSUE TITLE
Improving links of projects to other projects or to releases

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#210]
_Updates from discussion in [...]_

(In edit mode) When linking releases (and sub projects) to a project, the same release or sub project (or both) can be linked multiple times. The user should not be allowed to do that and a warning message should appear explaining that this request is not completed. [resolved, see comments below]

another effect is that if there is the same relation object (target) with a different project relation in two relations, the linked project view is not containing "the second relation" (whatever second relation means). Point here is to check if that is actually wanted/unwanted. [resolved, see comments below]

With this ticket a small modification could be applied: The link names "referred" and "contained" are not self explaining and should be renamed. No super proposals for rename but maybe: [remaining item]
* "is-sub-project" (contained)
* "is-related-project" (for referred)

Also relation unknown should not be default (but contained or is-sub-project). [remaining item]

**Comment by mcjaeger** [comment]
(from discussion) thrift service could reject relation creation, if ... - unclear. Idea to have the ticket only at first to rename relations and to remove unknown and do "is-subproject" then.

**Comment by mcjaeger** [comment]
Update (discussion): testing reveals that adding the release twice does not work, because it is a map, where the release id is the key. In fact it overwrites the entry, since an entry is put again to the map with same release id

**Comment by mcjaeger** [comment]
Update (discussion). Testing for linked projects: actually adding the project multiple times, the later entry overwrites the previous on, since this is also a map.

**Comment by mcjaeger** [comment]
Update from E-Mail: let's discuss contained, statically, dynamically linked.

**Comment by alex-evo** [comment]
so, is this issue "Ready", or do we need to discuss first?
