### ISSUE TITLE
Adding product version in the overview listing

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#220]
In the main listing in the project view, the main listing is missing the project version (at most other occasions, the version is added to the project name. What happens is that users add project entries with the same name but not with the version number. As such, there will be a number of entries with the same name and users need to open the entry to find the actual one.

Attached a screenshot.

![image002](https://cloud.githubusercontent.com/assets/3418977/18146679/461057c4-6fd1-11e6-8fb7-540165f0ede7.png)

Then there is a small layout issue which is that the version is added without a space character to the project name at the detail view (looks odd).

![image001](https://cloud.githubusercontent.com/assets/3418977/18146685/510ef568-6fd1-11e6-9708-09f3d9668580.png)

**Comment by maximilianhuber** [comment]
Is related to #230
