### ISSUE TITLE
Project list: filter use results in lists limited to 25 entries

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#221]
(requires testing because seen in commit version 32780d36). If the project filter is applied with a group value (formerly department), then the resulting listing is limited to 25 entries (although there are many more entries).

**Comment by heydenreich** [comment]
Testing confirms the above finding for all filters. Whenever a filter is applied, only 25 documents are found.

**Comment by heydenreich** [comment]
The limit on the number of results that couchdb-lucene returns can be set in `build-configuration/resources/couchdb.properties` . E.g. setting the limit to 100 can be done by adding 
`lucenesearch.limit = 100` to the mentioned file.

If the limit is not set, the default of 25 applies. This was the case so far.

Which limit is a good one to use?

**Comment by heydenreich** [comment]
Michael's  suggestion ` lucenesearch.limit = 150`
-> test this limit in a system with many documents to see whether the speed is ok
