### ISSUE TITLE
Project license information crashes if copyright listing is missing

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#222]
It is about the generation of the license information text file for a project.

If a component license information XML file of a release is missing the copyright section (what can apparently happen), the application returns an empty page (and no text file) - giving the impression it crashed.

The application should recover from this by writing into the generated file that no copyright information is available, similar to what happens if no file attachment of the release is found at all. 

Same coverage with missing or inconsistent information leading to an exception case could be applied with licenses.

**Comment by alex-evo** [comment]
Cannot reproduce. The current master handles missing copyright and license information just fine. Please retest and close or provide a failing example file.

**Comment by mcjaeger** [comment]
I think it was fixed once.
