### ISSUE TITLE
Table export of projects (the one the user can download) extensions

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#223]
In the project main listing view, the user can get an export of projects as a table document (for use with libre office for example) . Following enhancements are proposed:

* The export should reflect the actual selection / filtering in the project view.
* The export should also contain a possibility to list the linked releases with release information. 

For the second point, the desired output is denormalized: this means roughly the following structure
```
| project1 | project attributes ... | release1 linked to project1 (with component name) | release attributes ... |
| project1 | project attributes ... | release2 linked to project1 (with component name) | release attributes ... |
| project1 | project attributes ... | release3 linked to project1 (with component name) | release attributes ... |
| project2 | project attributes ... | release1 linked to project1 (with component name) | release attributes ... |
```

**Comment by heydenreich** [comment]
Another requirement is that the export respects the current filter. 

This is only partly implemented with components and projects (!) already: the "keyword search"-JS-filter is respected, the other filters are not.

**Comment by heydenreich** [comment]
Which linked releases should be listed: only the releases directly linked to the project?

**Comment by mcjaeger** [comment]
yes. otherwise it would be redundant, because then, the linked sub projects will be likely listed too as separate entry.
