### ISSUE TITLE
Projects detail: show all fields from edit view also in summary tab / pane

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#224]
When editing a project a creating a new one, the user may fill out project visibility or project state. However these fields are not visible in summary view.

All fields in the edit view should be visible in summary view, because otherwise the use needs always to switch into edit mode.

**Comment by heydenreich** [comment]
All project fields are visible in details view, also project state and visibility.

**Comment by heydenreich** [comment]
![image](https://cloud.githubusercontent.com/assets/14327740/18468492/81859a9e-79a4-11e6-8070-35b600169fbc.png)

**Comment by heydenreich** [comment]
Testing again shows: it already works.

**Comment by heydenreich** [comment]
display externalIds in details view
