### ISSUE TITLE
release deletion: ajax fails to remove row from data table

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#232]
In the details view of a component, tab `release overview`:

if clicking on the trash bin to delete a release, the release is successfully deleted in the database, but the row is not removed in the UI.

When using dataTable  no error is written to the JavaScript-log. When using DataTable the error "row is not a function" is written to the log.
In all other view.jsps DataTable is used the same way and it works fine.

**Comment by alex-evo** [comment]
duplicate to #268
