### ISSUE TITLE
adjust css of navigation bar

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#239]
aui css defines border, border shadow, box shadow of navigation bar

has to be overwritten in main.css: no borders

**Comment by mcjaeger** [comment]
hello, just how we did this in the discussion
![036 oss sw360 20160920 screenshot ui corrections](https://cloud.githubusercontent.com/assets/3418977/18663496/fa47af74-7f1e-11e6-94ed-8373ceab7bc7.png)
