### ISSUE TITLE
Display filter and name filter

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#256]
For projects and components, the name filter now searches for begin-strings of contained words, i.e.  "Apache Tomcat" is found, when you search for "tom", which is very nice. But, it is not found if you search for "omcat", which is ok, I think.

But the display filter shows a different behaviour: It only matches the begin string of the first word. I.e. "Apache Tomcat" is found, if you search for "apa", but not if you search for "tom". 

Should we make that more consistent? It would be easy to let the Display Filter search for substrings  of the project/component name (by removing the "^" from the regex) but that would not be totally consistent with the name filter.

Maybe it would also be possible to make it perfectly consistent with the name filter?

**Comment by mcjaeger** [comment]
confusing is that the display filter is prefix only, but could use component filer. Reopen if necessary
