### ISSUE TITLE
enum for project-release relation?

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#257]
It feels strange that we have enums for the project-project relationship and for the release-release-relationship, but not for the project-release-relationship. The latter is described by a string. 

Do we need more structure here?

This would of course mean that we have to migrate existing data...

**Comment by mcjaeger** [comment]
is it about 

```
    31: optional map<string, string> releaseIdToUsage,    //id, comment
```

-> "usage" should be enum instead of string

**Comment by alex-evo** [comment]
so what values should the enum have?

**Comment by mcjaeger** [comment]
(from discussion) we need a list of all used relation values since it is free text at the moment. Then we could do a proper migration.

This requires  a good jscript query at first.

**Comment by mcjaeger** [comment]
we would need beside the relation enum also the approval enum:

1) 
enum MainlineState {
    OPEN = 0,
    MAINLINE = 1,
    SPECIFIC = 2,
    PHASEOUT = 3,
}
-> add DENIED = 4
-> move to sw360.thrift

**Comment by alex-evo** [comment]
what would be a good default value for mainlineState of a migrated project-release relationship?
