### ISSUE TITLE
After deleting a project from any page, the view returns to first page

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#271]
Under Projects tab navigate to any page different from First, and delete a project. Expected result is that the listed page is recreated and remains the same (if it is not the last and didn't contained single item). Actual result is that the first page is displayed instead which seems quite annoying, e.g. if the user wanted to delete or edit another project from the same page.

The same happens when there is a filter applied with multiple pages result.

**Comment by alex-evo** [comment]
I have the suspicion that this can be achieved by simply adding the parameter `false` to the call to `draw()` at projects/view.jsp:350
`oTable.row('#' + projectId).remove().draw(false);`
Or maybe read the page number, then remove the row, and set the page number again.
One should try and test.
