### ISSUE TITLE
At Readme-OSS / Disclosure Document creation: Make Releases Selectable

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#276]
At readme generation: The user should be able to 

1. select the releases to be included for the generation. This shall  be a list in a pop-up window (similar to a "do you really want to delete" dialog)
2. If there are multiple SPDX files for example, suitable for generation, allow the user to select one o fthe available (with a pop-up menue maybe)

Right now, there maybe multiple license information files from different users and also there may be components. And some components no useful license information - then the user would be forced to manually remove them from output. For the text-based files it might be OK, but for HTML or Word, this may turn out to be cumbersome.

**Comment by alex-evo** [comment]
Is it necessary to enforce selecting one and only one license information file per release?
