### ISSUE TITLE
Moderation requests with more info: comments, etc.

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#277]
After rejecting a couple of moderation requests, I realized that the moderation requests should have comment fields. For the rejection dase, there should be information for the sumitting user why the moderation request was rejected.

The use case would be as follows:

The moderator can fill out a comment field. By clicking reject (or accept or postpone), the entered text to the comment field is submitted and saved with the moderation request. 

The submitting user can see the comment when looking at her open moderation requests, regardless which status (like accepted, rejected, postponed.

Also needed:

* Comment for the submitter of a moderation request when submitting
* In the moderation request detail view: show submitter, submitter group, comment and date
* In the moderation request listing, show date, submitter e-mail, submitter group
* In the moderation request listing: ommit long list of moderators, shorten to maybe two lines max .

Then there was the question for some never changing value ...
* In the moderation request listing, there is for all Action the value "TODO" what does that mean?

**Comment by mcjaeger** [comment]
this implies that moderation request can be shown (name could be clicked) also after closing, what is not the case right now.

**Comment by maximilianhuber** [comment]
Moderators should not be able to delete moderation requests, without giving the requester the chance to review it.

**Comment by mcjaeger** [comment]
I am not sure, from a workflow point of view, yes, but from a data curation point of view, sometimes moderation requests are useless or trivial. also sometimes a user creates a moderation requests but does not log in again for a longer time.

I would not say that moderators must be able to do so, but clearing admins and ecc admins and other admins involved in the moderation request round should be able.
