### ISSUE TITLE
Merging Releases of the two Components

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#278]
Still, we have the following situation:
* one component name "apace commons logging"
* one component name "commons logging" with vendor "apache" at some of the releases. 
-> both having added releases to them

Now it is a very difficult task to merge the two, because basically, releases of one component need to be recreated at another component entry, then the attachments and then updating project information. What would be needed is some sort of release migrator, moving it from one component to another.

**Comment by mcjaeger** [comment]
could be also considered for licenses and vendors!

**Comment by mcjaeger** [comment]
(from discussion)

There are two use cases:

* duplicate component -> migrate the release to another component
* duplicate release -> merge two release documents to one 

### Duplicate Component

we have sorted out the following points:

* first of all, it will be based on selecting a particular release from the origin component to the target component. The user shall need to move each release one by one.
* Then there is the naming conflict possible: What to do with the release versions the same? -> second use case

#### How to deal with the individual fields

* if thereis no conflics, references to the component are updated, and then it should b OK.
* if there is a version name conflict: operation is cacenlled, clearing admin needs to change the version of the release first.

### Duplicate release

Case is that inside a component there are two release which should be merged to one. use case is maybe also a preceding transfer of one release to another.

* There should no walk through the project to reassign release ids, rather a release holds an array of old release documents Queries need to be changed accordingly.

* Then a three way merge view allows the user to select to chhose the attribute values from

* references are merged anyway there should not be conflicts. If there a duplicates, then the result will be one entry in the resulting release.

**Comment by imaykay** [comment]
Ticket needs to be finished by another team member. PR #602 implements nearly the complete component merge, in which the migration of releases is implemented as well. But it has to be tested carefully as my knowledge of the datastructure is limited due to the short time in the project.
Merging of releases is still open though it should be easy to implement with a little help of the merge wizard framework.
