### ISSUE TITLE
Provide Friendly URLs

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#28]
Right now sharing links is difficult as direct / clean URLs for components or projects do not work.

Solution could be http://www.liferay.com/de/community/wiki/-/wiki/Main/FriendlyURLMapper

Goal is that Users can share (friendly)  URLs betwen each other to projects, releases, etc.

As an alternative:
* provide the database ID of that item
* provide a means to enter this database id
* maybe provide that fields to call a specific document in the search pane?

**Comment by mcjaeger** [comment]
apparently should be a friendly URL to page including information / or URL suffix that represents a portlet parameter (for example project name)

**Comment by mcjaeger** [comment]
postponed after contribution about linking could solve this

**Comment by alexbrdn** [comment]
here's another liferay wiki page 
https://web.liferay.com/community/wiki/-/wiki/Main/Friendly+URLs
