### ISSUE TITLE
Get Rid Of dataTables-1.9.4.js

### ISSUE THREAD

**Issue by alexbrdn** [sw360/sw360portal#284]
There are two versions of jquery datatables plugin used in sw360. Most of the code uses newer 1.10.7, but there are still a couple references to the older version 1.9.4 which had an incompatible API. Those usages need to be ported to the new version and the old one should be removed from the project.

**Comment by mcjaeger** [comment]
could be closed by some undisclosed source

**Comment by mcjaeger** [comment]
done with webjars

https://github.com/sw360/sw360portal/pull/369
