### ISSUE TITLE
Improved Linked Projects and Releases in Project Portlet

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#287]
Edit: please see conversation on what is open.

There are a number of issues now with the display of the table view. Maybe this could be improved for displaying larger projects.

1. add column for type: component (OSS, COTS, Freeware, ...) or proejct type (Internal, Product, Project, Service)
2. Add column for clearing state
3. Presort listing on every level by name.
4. Do not overrun component or project name in the line (so line breaks spoil the display), but shortcut name with '...' after some number of characters, so the line break will not occur. Assuming display width of 1280.
5. Add project attribute project clearing state with values 'open|progress|closed'

**Comment by mcjaeger** [comment]
point 5 is open whether set automatically or manually.

**Comment by alex-evo** [comment]
question: given that generation of license info will get an own page when #280 is merged, should the new columns (Type, Clearing State) be added to that page, too?

**Comment by AndreaVogler** [comment]
add 1: Type (OSS oder COTS) missing in **project page : Clearing Status**

add 3: Sorting in **project page : Linked Releases And Projects** according to release only not by a combination of vendor/release

**Comment by AndreaVogler** [comment]
add 1: Type (OSS oder COTS) missing in project page : Clearing Status

add 3: Sorting in project page : Linked Releases And Projects according to release only not by a combination of vendor/release

Discussed with Michael Jäger / Marco Wagner on 2017-01-16

**Comment by mcjaeger** [comment]
hi, please use @mcjaeger for referring to me so I am getting a notification.

For adding the Type (OSS|COTS|...) we should use short names and not "Open Source Software" and "Commercial". At the sametime, this should be changed also on the main listing of the component listing of the component portlet.

**Comment by mcjaeger** [comment]
still open: 

> For adding the Type (OSS|COTS|...) we should use short names and not "Open Source Software" and "Commercial". At the sametime, this should be changed also on the main listing of the component listing of the component portlet.

**Comment by mcjaeger** [comment]
retested:
* on component entry the short names are used
* in the main listing also shorter naming is used.
