### ISSUE TITLE
Replace usages of JS alert()

### ISSUE THREAD

**Issue by alexbrdn** [sw360/sw360portal#295]
Usages of JavaScript function alert() should be replaced with jquery's $.alert() throughout the code.

**Comment by maxhbr** [comment]
assigned to @stevinus1

**Comment by mcjaeger** [comment]
(from discussion) change became a little more extensive because of requires js as a wrapper is needed for the jquery calls.

**Comment by mcjaeger** [comment]
@alexbrdn @maxhbr can we close this now given the PRs we have had on the JavaScript refactoring?

**Comment by alexbrdn** [comment]
No, there are still multiple calls to `alert()` in the codebase.

**Comment by mcjaeger** [comment]
closed because of migration issues.
