### ISSUE TITLE
Performance of Components CSV Backup is Terrible

### ISSUE THREAD

**Issue by alex-evo** [sw360/sw360portal#308]
Backing up components from the Admin/Component Upload page takes awfully long for around one thousand components. A probable reason is that `ComponentSummary.summary()` fetches all releases from the database every time it's called. And it is called once for every component. That's a lot of database roundtrips.

**Comment by maximilianhuber** [comment]
Did you had a look at https://github.com/sw360/sw360chores/pull/12 which implements a generic docker based backup of all persistent data. This generates also an tarball containing the couchdb files.

There is also a second backup strategy implemented which will soon be contributed. It uses the project [danielebailo/couchdb-dump](https://github.com/danielebailo/couchdb-dump), which contains a script that is able to dump and restore the contet of an database on couchdb as json via HTTP. This will be also a PR directed to the chores-repository.

**Comment by maximilianhuber** [comment]
The second variant is now also contributed as https://github.com/sw360/sw360chores/pull/15

**Comment by mcjaeger** [comment]
there are many different ways now to backup stuff
