### ISSUE TITLE
How to handle finished moderation requests

### ISSUE THREAD

**Issue by AndreaVogler** [sw360/sw360portal#313]
Moderation requests which have been finished (approved or rejected) should not be visible any longer in the list of moderation requests that are still open.
Proposal is to remove them or provide a separate list with completed requests.
This increases the visibility of the open requests and make handling of them easier.

**Comment by mcjaeger** [comment]
* They should be deleted by the publisher from a workflow point of view, but also clearing admin and admins should be able to delete these.
* proposal is to show the open only ("in progress" and "pending") on one tabbed pane (we are using vertical tabs on the left) and the closed ones ("rejected" and "approved") on a another tabbed pane.
