### ISSUE TITLE
Mandatory fields for components & releases

### ISSUE THREAD

**Issue by AndreaVogler** [sw360/sw360portal#314]
'Short Description' and 'Homepage URL' should be mandatory fields for a component.

'Download URL' should be a mandatory field for a component.

These fields are relevant for clearing & ECC identification and for search.

**Comment by mcjaeger** [comment]
it is about releases obviously...

The difficult part is that we have had a number of fields mandatory and in the discussed we pulled out "mandatoriness" from fields.

Proposal: can we configure fields to be mandatory for an instance easily?

**Comment by AndreaVogler** [comment]
description should be mandatory for COTS & OSS & Freeware & Internal
Home Page should be mandatory for COTS & OSS & Freeware
Download URL should be mandatory for OSS only

**Comment by mcjaeger** [comment]
replaced by this: https://github.com/sw360/sw360portal/issues/429
