### ISSUE TITLE
Project with project clearing state 'closed' must not be changed any more

### ISSUE THREAD

**Issue by AndreaVogler** [sw360/sw360portal#323]
The new property 'project clearing state' has the values : open, in progress, closed.
When a project is in closed state no changes should be allowed anymore for a 'normal' user, e.g. removing or adding releases.

The project then might have already been delivered to customers and also the ReadmeOSS. If a project gets changed after release this causes inconsistencies with already delivered products.

Only experienced users (i.e. clearing admins) might be able to set the state back to 'in progress', do some distinct change and then put it back to 'closed'

This issue has been discussed with Michael Jäger and Marco Wagner on 2017-01-16.

**Comment by mcjaeger** [comment]
(from discussion) should be clearing admins only. Currently, moderation request is created, but there should be zero possibility of edit for users.

**Comment by mcjaeger** [comment]
note that users with still write ability could unlock a project by changing the state - which is required and good.
