### ISSUE TITLE
Excel export for one specific product

### ISSUE THREAD

**Issue by AndreaVogler** [sw360/sw360portal#325]
SW360 provides the feature to generate an EXCEL export for the complete or a filtered set of products. This is good but somehow complicated to get the required information for a specific product. There are so many columns and you need to adapt it before you really can work with it, e.g. if you just want to have a short report of the current status which you can send to other people to do some discussions/checks.

I'm missing the feature to create an EXCEL report for one specific product with less information than provided by the general EXCEL report:
- component  name
- version
- type (OSS / COTS or other product)
- clearing state
- security vulnerability
If one of the entries is another product the entry should be expandable to see the next level of components.
See attached example file.

**Comment by AndreaVogler** [comment]
[Product_EXCEL_Example.xlsx](https://github.com/sw360/sw360portal/files/713351/Product_EXCEL_Example.xlsx)

**Comment by mcjaeger** [comment]
addin ECC Infos: AL, ECCN, Status, Approving person, Date, Approving Status

**Comment by alex-evo** [comment]
- While we're at it, rename "Export Excel" to "Export Spreadsheet"

**Comment by alex-evo** [comment]
I'm not entirely sure what the consensus is on what fields should be exported. I've created the PR #341 where I added the same export functionality that already exists, but limited to the selected project and its subprojects. I would appreciate your feedback.
