### ISSUE TITLE
Validate license id with short name

### ISSUE THREAD

**Issue by toedter** [sw360/sw360portal#329]
Currently the short name of a license is used as (couchbase) id. But the API does not validate if id and short name match when a new license is created. So it is possible to create a license with id "apache20" and shortname "mit".

**Comment by mcjaeger** [comment]
(from discussion) short name should be deprecated and not used anymore.

**Comment by mcjaeger** [comment]
apparently will be solved when we will have a commit from an undisclosed source using SPDX tools and SPDX license list import

**Comment by maximilianhuber** [comment]
> apparently will be solved when we will have a commit from an undisclosed source using SPDX tools and SPDX license list import

No, this is not the topic of #370.

To solve the issue mentioned by @toedter one has to check whether the ID equals the shortname (if set) everytime one creates or updates a license.

An alternative more complete solution would be to make the ID of the License an UUID again. But this will then interfere with https://github.com/sw360/sw360portal/issues/19 which was implemented via https://github.com/sw360/sw360portal/pull/135.
