### ISSUE TITLE
LicenseInfo Service: template files from /etc/sw360

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#330]
Redeploying the license info service losses custom license info generation templates and the ones that were available at compilation / packaging time of the *.war file is in again.

The templates shall be also considered from the /etc/sw360 folder, so the redeployment of the service does not require adaptations in /opt/sw360/webapp/licenseinfo/WEB-INF/classes .... or whatever the actual path is.

**Comment by mcjaeger** [comment]
looks weirdo:
https://docs.spring.io/spring/docs/2.0.x/javadoc-api/org/springframework/ui/velocity/VelocityEngineUtils.html

**Comment by maximilianhuber** [comment]
This should already work, if the templates are loaded with our util function `CommonUtils.loadResource()`. Please retest.

**Comment by alex-evo** [comment]
The templates are _not_ loaded with `CommonUtils.loadResource()`. See e.g. https://github.com/sw360/sw360portal/blob/master/backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/LicenseInfoGenerator.java#L55
