### ISSUE TITLE
Spreadsheet export : one row for each contained / linked project

### ISSUE THREAD

**Issue by AndreaVogler** [sw360/sw360portal#335]
An EXCEL report with the option 'Project with linked releases' for each release creates one row for each release in the EXCEL sheet.
All linked project are listed in **one** column separated by comma.

Please handle linked projects in the same way like linked releases and create in the  EXCEL report one row for each linked project as well.

**Comment by mcjaeger** [comment]
yes, whould be two stage denormalized.

**Comment by mcjaeger** [comment]
problem is that sub projects and releases are orthogonal

**Comment by mcjaeger** [comment]
continued therehttps://github.com/sw360/sw360portal/issues/435
closing here
