### ISSUE TITLE
Moderation request warning is missing when editing ECC of an own created release

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#339]
When editing ECC Details of an own release, the message "Moderation request was sent..." is displayed only after pressing the Update Release, while other users are warned that they will create a moderation request, before updating the release.

**Comment by mcjaeger** [comment]
note that a mix edit of "normal data" and ecc information also creates an ecc moderation request.

**Comment by mcjaeger** [comment]
(discussion on the roles, currently inside:)
USER
CLEARING_ADMIN
ECC_ADMIN
ADMIN

**Comment by mcjaeger** [comment]
(discussion) display warning at the respective editing fields when adding ECC relevant information

**Comment by mcjaeger** [comment]
adding a conditional: if role not at least ecc_admin then write warning on page.
