### ISSUE TITLE
Wrong link to README in the wiki (easy solution)

### ISSUE THREAD

**Issue by silverhook** [sw360/sw360portal#347]
On https://github.com/sw360/sw360portal/wiki

The `README.md` link in this part:

> # Documentation
> 1. For development, please see the README.md file of the project first.

should be fixed so it points to the right document, namely here:
https://github.com/sw360/sw360portal/blob/master/README.md

I haven’t checked, but there might be other bugs of a very similar nature in the wiki as well.

**Comment by mcjaeger** [comment]
thanks for pointing out! - done
https://github.com/sw360/sw360portal/wiki
