### ISSUE TITLE
License search in Component Edit View (Select License) is case sensitive (pictures inside) 

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#348]
Component search is case insensitive and filters the list automatically.

Case-sensitive  search is not very intuitive and inconsistent with other search fields.

![2016-12-07_12_46_47-https___sw360 siemens com_-_components_-_sw360_-_vimperator](https://cloud.githubusercontent.com/assets/3418977/23260277/49fb2442-f9d1-11e6-8b4a-a949e33427b1.png)

![2016-12-07_12_47_21-https___sw360 siemens com_-_components_-_sw360_-_vimperator](https://cloud.githubusercontent.com/assets/3418977/23260263/3fa8e006-f9d1-11e6-88ca-c06048c24e3e.png)

**Comment by Herschdorfer** [comment]
we can close this here as well now.

**Comment by mcjaeger** [comment]
yes, closing
