### ISSUE TITLE
Spreadsheet Export for Projects may contain multiple column headers with the same ID

### ISSUE THREAD

**Issue by innerjoin** [sw360/sw360portal#354]
If the export contains information of more than one table (e.g. projects and its linked releases) and both of these tables contain the same attribute, the spreadsheet has multiple columns with the same name.

Should be fixed together with #353

**Comment by mcjaeger** [comment]
please note that there is not technical reason to fix this together with #353 as they two issues are technically independent from each other.

**Comment by innerjoin** [comment]
@mcjaeger you are right, this issue is for me a severe one whereas #353 is not.
