### ISSUE TITLE
Documentation of Search Functionality

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#361]
For the different search functions, the search functionality seems to be different, documentation would be helpful.

Also question is if there can be use of wildcards.

Especially, users are confused how the filter works for projects, because it seems to find
* entire words
* a match using .startsWith("...")
* sometimes entire words and starts with are not found by filter, by b search (example "Web SDK")

**Comment by max-wittig** [comment]
## Just to provide an example for this issue
While the `Testing Search Functionality` component was found with Quick Search (just using a part of the component name)

![found-quick](https://user-images.githubusercontent.com/6639323/32041096-3ef9b838-ba33-11e7-9ecb-4638edb74b65.PNG)

---

### When trying to add a release to a project, the search functionality seems to be different

![image](https://user-images.githubusercontent.com/6639323/32041205-924d2dee-ba33-11e7-83a8-60785ba2b168.png)

---

### However the component can be found, if just the beginning of the string is used
![image](https://user-images.githubusercontent.com/6639323/32041340-fee1edaa-ba33-11e7-8630-b6f2b11bdf1c.png)

@AndreasSchirm

**Comment by mcjaeger** [comment]
see also this as input: https://stackoverflow.com/questions/17839053/how-to-perform-a-lucene-query-containing-special-character-using-queryparser

**Comment by mcjaeger** [comment]
thanks to Linus: https://github.com/sw360/sw360portal/wiki/User-Search
