### ISSUE TITLE
remember login user

### ISSUE THREAD

**Issue by AndreasSchirm** [sw360/sw360portal#374]
## Actual
actual login screen is:
![img_2017 04 20_ 16 15 53](https://cloud.githubusercontent.com/assets/14091910/25235196/bf3eef60-25e4-11e7-951e-c7e63514b469.png)

## expected behavior
add a remember user checkbox to login in screen that will autofill the user for the next session.

**Comment by mcjaeger** [comment]
Thanks for contributing here to the discussion of sw360.

I think it is there but needs to be enabled on the instance (otherwise the checkbox will not show).

![screen shot 2017-05-03 at 10 34 31](https://cloud.githubusercontent.com/assets/3418977/25653205/2d0f42cc-2fec-11e7-82bb-36ee402e1667.png)
