### ISSUE TITLE
Add Help Tips for Enums and Fields

### ISSUE THREAD

**Issue by alexbrdn** [sw360/sw360portal#394]
(as discussed in our weekly call)

Some enum values that are used in object properties are not self-explanatory. For example, it is not at all obvious what some values of MainlineState (OPEN, SPECIFIC) mean.

To remedy some confunsion, it is proposed to create a custom tag that will take an [sw360 thrift] enum class as a parameter and create an `(i)` icon with a tooltip explaining the meaning of different values. This tag should then be inserted at various places where the values of enum types are displayed or edited.

It would probably be wise to somehow only render the help text once per page and call show it via javascript, otherwise a long table may include thousands of copies of the same help tooltip.

Addition from Michael: Could be actually more sort of help tool tips for fields to explain field value interpretation.

**Comment by mcjaeger** [comment]
I tried to make a start for providing the content here:

https://github.com/sw360/sw360portal/wiki/User-Fields-and-Terms
