### ISSUE TITLE
Vulnerability Portlet overview takes long to render (if filled with many entries)

### ISSUE THREAD

**Issue by maxhbr** [sw360/sw360portal#411]
Currently the vulnerability portlet shows a **sorted** list of all vulnerabilities. And each entry contains a link to the corresponding vulnerability, which **is generated by an JS function**.

Profiling shows that these two features are the problem which causes the long loading time:
![screenshot](https://cloud.githubusercontent.com/assets/1187050/26203321/0dea8294-3bdb-11e7-9f7d-1c44971d88df.png)
(with ~230 vulnerabilities)

**Comment by maximilianhuber** [comment]
The problem is not the `createDetailURLFromVulnerabilityId(...)`. The problem in the first half is that the result is generated via
```
result.push(...);
result.push(...);
result.push(...);
...
result.push(...);
```

**Comment by alex-evo** [comment]
In that case, we have this idiom used in many places

**Comment by alex-evo** [comment]
It's probably worth trying to convert this to a huge array literal.

**Comment by maximilianhuber** [comment]
I have tried to reformat it to
```
var result = [
{....},
{....},
...
]
```
This does not change the load time at all.

**Comment by alex-evo** [comment]
well, then, I guess it's time to generate the whole table on the server side instead of generating the JS which generates the table on the client

**Comment by maximilianhuber** [comment]
datatables suggests [server side processing](https://datatables.net/manual/server-side) for tables with `many thousands of data rows`. Maybe one should have a look at that.

**Comment by maximilianhuber** [comment]
The webjars version takes even slightly longer then the old version: "750ms -> 850ms" for the `load()` function.

**Comment by maximilianhuber** [comment]
Maybe it is an alternative to simply remove that portlet/overview. I am not sure whether there is an usecase which requires this portlet.

**Comment by alex-evo** [comment]
The problem is that the projects and components tables are built the same way. They also have the same bad performance with thousands of rows and we don't want to get rid of them.

**Comment by mcjaeger** [comment]
is it better now? just because of: https://github.com/sw360/sw360portal/pull/430

**Comment by bs-jokri** [comment]
Suggestion: Just use the table for search results. Only after a search was started a table with the results is shown.

**Comment by bodetc** [comment]
GUI Mock-Up for the presentation:
![vulnerabilities-search](https://user-images.githubusercontent.com/22469333/27678604-1581f1d0-5cb6-11e7-89e6-42041dfd59c6.png)

**Comment by mcjaeger** [comment]
@bs-jokri since #564 is merged could we close this issue?
