### ISSUE TITLE
Adding more release relations for projects

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#420]
There should be more release relations for projects, because there will be some demand to express `contained` in a more precise way in order to determine the impact of licensing.

* Contained
* Dynamically linked
* Dynamically linked - Python
* Dynamically linked - DLL
* Side by side 
* Side by side - Dynamically linked
* Side by side - Separated execution
* Statically linked
* Stand alone
* Internal use
* Optional
* To be replaced

**Comment by mcjaeger** [comment]
(from discussion)
 the variants ahve not so much value of dynamic and side by side, so it should be:

* Contained
* Dynamically linked
* Side by side 
* Statically linked
* Stand alone
* Internal use
* Optional
* To be replaced

**Comment by alexbrdn** [comment]
One thing to note: what is called "Is a subrelease" in UI, is called `CONTAINED` in the DB. So, "Contained" is already there, in a way.
