### ISSUE TITLE
Text colour for filter values too bright (hard to read)

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#423]
(please test all portlets not just projects)

a picture is worth more than 100 words:

![036 oss sw360 20170529 screenshot text coulour for filters](https://cloud.githubusercontent.com/assets/3418977/26583083/048d1c6c-4544-11e7-8bda-f4a97c8a9897.png)

(let's make it black)

**Comment by bs-jokri** [comment]
rgb(85, 85, 85) -> target color
