### ISSUE TITLE
Just show approved reports for download

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#424]
In the clearing view of components -> release overview, please just show approved files for download.

Also add some more file info (who approved, who uploaded) to the tool tip which currently carries the filename.

**Comment by lepokle** [comment]
Hi @mcjaeger 
please have a look at the provided screenshots for clarification. The implementation is a result from the discussion last week:

Unapproved files are shown but are gray (the can be downloaded):
![clearing_report](https://user-images.githubusercontent.com/499823/28016315-2b326098-6574-11e7-92aa-41f14ef8eac0.png)

The tooltip shows more information for each state:
![tooltip_approved](https://user-images.githubusercontent.com/499823/28016314-2b2be510-6574-11e7-892d-a7a1ce977c8d.png)
![tooltip_rejected](https://user-images.githubusercontent.com/499823/28016316-2b331204-6574-11e7-978d-bd590d9c3463.png)
![tooltip_not_checked](https://user-images.githubusercontent.com/499823/28016317-2b383b62-6574-11e7-8b79-b9a61d1a2012.png)

Is that ok or do you want some changes, e.g.:
- disable download on gray items?
- really hide gray items (no quick information of rejected ones)?
- other?

Thanks!

**Comment by mcjaeger** [comment]
(from "monday"-discussion) let's go for the approved reports only for this display. But the mouse over is good!

**Comment by lepokle** [comment]
Alright!

**Comment by lepokle** [comment]
See pr #488

**Comment by imaykay** [comment]
PR has been merged a few days ago...
