### ISSUE TITLE
Project Listing: Add Clearing State

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#426]
The listing of projects show the project state, however, for the work, if there is the clearing state of the project? That would be more relevant. 

proposal make circle with color for project state
* green for active
* grey for inactive

Add project clearing state
* red for open
* yellow for in progress
* green for done

with captions  "PS" with mouse over "Project Status" and "CS" with mouse over "Clearing status"

**Important:** Add the project state also to the listing of linked releases and projects.

**Comment by ChristophNiehoff** [comment]
@mcjaeger I have two questions:

1.)   In the projects listing I added coloured boxes for project and clearing state (see attached picture). Is the design ok or should I change it?
![untitled](https://user-images.githubusercontent.com/10673021/28127706-c34a211c-672d-11e7-87b5-4a315e9aab44.png)

2.) In the listing of linked releases and projects, shall I just add the project state as a text, or should there also be coloured boxes?  In the second case, the column "clearing state" can take the values ("New", "Sent to Fossology", "Under clearing", "Report available", "Approved"). How should the colours be assigned to these values?
