### ISSUE TITLE
Inspect usage of org.springframework.* dependencies

### ISSUE THREAD

**Issue by bs-jokri** [sw360/sw360portal#434]
We have the dependencies 
org.springframework:spring-beans 4.1.5.RELEASE 4.3.8.RELEASE
org.springframework:spring-context 4.1.5.RELEASE 4.3.8.RELEASE
org.springframework:spring-webmvc 4.1.5.RELEASE 4.3.8.RELEASE

which are used in src-fossology. However, it is not clear for what we need spring dependencies there. Should be clarified.

**Comment by bs-jokri** [comment]
relates to #416

**Comment by mcjaeger** [comment]
it seems like the fossology service is different than other service. We would need at least documentation why the spring context (etc) is used and how it is used.

**Comment by mcjaeger** [comment]
closed by https://github.com/sw360/sw360portal/pull/416
