### ISSUE TITLE
Edit view for attachment needs rework

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#437]
Improving the edit mode view (besides the plain listing in view mode):

* major problem is that file names are truncated and mouse-over for the file name is missing. If uploading a set of files, have a common beginning, then, the user cannot distinguish the files afterwards
* use of space in this table is not optimal. also labels are reoccurring every row which maybe obsolete or could be reduced.
* newly added attachment could be marked as being new (in addition to existing ones). maybe by some use of colours or an icon.
* uploader and approver are not visible in edit mode

Best would be to have a similar table like the data tables: allowing for sorting at each column title, page size settings, etc.

**Comment by lepokle** [comment]
![image](https://user-images.githubusercontent.com/499823/29173187-cac4a2ac-7de2-11e7-9207-ac7485962b20.png)

New Features:
- Organized as sortable datatable
- full filename is displayed
- nearly all information of an attachments is displayed
- tooltip with expanded text for all columns
- highlighting for just uploaded attachments
- deletion bug fixed
- popup dialog for comment input to have more space

Removals:
- download is not possible during edit anymore (was event not working for just uploaded attachments before)

**Comment by lepokle** [comment]
See PR #530
