### ISSUE TITLE
Add project version to filters for projects

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#438]
When having collection of the same project or product with different version, search for a particular version is difficult, in fact it is possible to have a product with 30 versions. Then, picking one is difficult, because the filters do not allow for specifying the version.

Presumably, just adding a field for version beside the field name could be enough at the filters.

**Comment by imaykay** [comment]
I would not include any automatic wildcard extension. So if a users wants to find version "foobar" and just types "foo" into the new input field he will not find the project. But he can enter "foo*" and will find his project.

If we should add wildcards internally like during name-search just let me know.

**Comment by imaykay** [comment]
closed by #484
