### ISSUE TITLE
Add vulnerability state(s) and ECC states in clearing status in projects

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#440]
Currently, there is clearing state, mainline state and project mainline state, but missing would be:

* ECC state (all components have ecc info?)
* Vulnerabilitties (any open vulnerabilities?)
* Tracking of components (is the release actually being tracked by vulnerabilities?)

There should be another view besides clearing status which is "ECC Status" which displays classification info and approver 

For vulnerabilities, a new view exists

**Comment by ChristophNiehoff** [comment]
@mcjaeger 
It is not clear to me what exactly should be contained in the new view "ECC Status". Could you please clarify on what you have in mind?

Also: All the additions information should should be shown in the new "ECC Status" and the already existing "Clearing Status" stays as is?

**Comment by mcjaeger** [comment]
agreed issue is confusing, it is about:

https://github.com/sw360/sw360portal/issues/349

-> cloding this issue, as the vulnerability status is already there and the ECC status should have a new view.
