### ISSUE TITLE
Display filter name keeps filled out, but is not active

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#441]
Some inconsistency in the user guidance:
* go to components
* enter some display filter name
* click some  of the hits
* assuming it was not what searched for, jump back by browser back
-> value of display filter is filled out, but filtering is off, which is confusing
It would be good, if, once there is a value in the component filter, this values filters also.

**Comment by lepokle** [comment]
Applies for all tabs/quick filters (e.g. projects, ecc, licenses, ...)

**Comment by lepokle** [comment]
We just have to apply the filter on page load.
I'll have a look if the search field can be created as component that is used in all sites.

**Comment by lepokle** [comment]
@mcjaeger 
Short question: if one clicks the exportSpreadsheet button, the quick filter is reset to  nothing. Wouldn't it be better to disable it on quick filter input like it is done on 'Advanced Search' Input?

**Comment by mcjaeger** [comment]
(from discussion, maybe leave it as it is)

**Comment by lepokle** [comment]
Closed by PR #506
