### ISSUE TITLE
Clearign status numbers for releases dos not contain sub projects

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#446]
There can be projects with `0 0 0 0 0` which is in most cases just a container project that contains subprojects with releases. In this case it would be good to have the releases of the linked projects also in.

Also the consensus seem to change the view from the five numbers to `X of Y` like `23/50` meaning that 23 releases out of 50 are approved.

Adding to that: going over subprojects, the already async loading od the numbers will be super slow. Maybe there would be a way to load the numbers of the projects in batches (and not for all projects all at once)?

**Comment by imaykay** [comment]
Okay, while implementing the feature, questions around permissions arose:

Let's assume there are
* three projects (P1, P2 and P3)

and 
* two Users (U1 and U2).

U1 has the permission to view P1 and P2
U2 has at least permission for P2 and P3
P1 contains P2
P2 contains P3

Shall the clearing summary of P3 be included in the projects list view of U1 for P1? As probably one of the upcoming feature requests after this story will be: show me which subproject is the one that is missing its clearings this question can be answered easily for me. In this case you will have to show U1 that there is a project P3 which he should not know of. But if do not aggregate P3's clearing summary, U1 might think that everything is cleared and go ahead.

So: respect permissions in clearing summary or not?

**Comment by alexbrdn** [comment]
If I recall correctly, right now, all types of relations of projects to subprojects and projects to releases are followed in the counting of the five status numbers. I'd venture to say that this should remain so.

**Comment by mcjaeger** [comment]
I think it should be the global view on the numbers of project listing regardless of the permissions

regarding relation: I would be OK not to change it or consider relation, but it would be better to do so. But I would count only 'referred' or 'duplicate' as the ignoring relations, because 'unknown' might be generally there when it is meant 'contained'

**Comment by imaykay** [comment]
Alright, permissions are not checked and I ignore project relations "referred" and "duplicate" and release relations "referred".
