### ISSUE TITLE
Release name should be component name - and not editable

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#451]
Somehow, not obvious, but release names can be changed from component name. That would make problems. It should not be editable, the release name.

**Comment by alexbrdn** [comment]
I thought I'd heard from someone that that was a conscious decision (to make the name editable), but my memory is pretty dim on this.

**Comment by mcjaeger** [comment]
from me? (maybe ...) but that is the summary from our usage now that in fact from the usage experience it is confusing. Maybe we need more discussion on this what a good behavior for this would be.

**Comment by mcjaeger** [comment]
(from discussion) component name should be copied (and not user editable anymore) to the release name.

**Comment by maierthomas** [comment]
What about existing releases with not identical names?

**Comment by maierthomas** [comment]
@mcjaeger do we need to update all the existing release names with not identical names?

**Comment by mcjaeger** [comment]
I think we would need a migration script for this and the migration script with dry run mode. the script should output the diverging release names and then the user can decide to go ahead.
