### ISSUE TITLE
License Dialog should search for license short name as well

### ISSUE THREAD

**Issue by bs-jokri** [sw360/sw360portal#458]
When I try to link a license to a release the license dialog only searches for the long name of licenses. By that it is only possible to search eg for Eclipse ... instead of EPL or GNU instead of GPL
![license dialog](https://user-images.githubusercontent.com/13886571/27073223-65a10d44-5023-11e7-9703-2eb804333be7.png)

**Comment by Herschdorfer** [comment]
we can close this here also
