### ISSUE TITLE
Store attachments in external repository

### ISSUE THREAD

**Issue by maxhbr** [sw360/sw360portal#465]
If one plans to sync data from an artifact repository server like Sonatype Nexus or Artifactory it would be redundant to save the source/binary attachments also in SW360. It might even be not possible due to the size of the attachments.

This could be solved by introducing remote attachments, which might be verified by their hash (which can be obtained from the repositories vie REST, or it could be provided for the upload).

**Comment by bs-jokri** [comment]
superseded by https://github.com/sw360/sw360portal/issues/639
