### ISSUE TITLE
Licence search is case sensitive

### ISSUE THREAD

**Issue by Herschdorfer** [sw360/sw360portal#478]
When i search for a license for adding to a component. then this search is case sensitive.

**Comment by bs-jokri** [comment]
Relates to #458

**Comment by maximilianhuber** [comment]
Duplicate of https://github.com/sw360/sw360portal/issues/348

**Comment by mcjaeger** [comment]
But thanks for contributing an issue to us! :)

**Comment by Herschdorfer** [comment]
NP :)

**Comment by Herschdorfer** [comment]
made a fix #479
