### ISSUE TITLE
Session message on error should be red (instead of green)

### ISSUE THREAD

**Issue by maximilianhuber** [sw360/sw360portal#49]
If one shows a banner using `com.siemens.sw360.portal.portlets.Sw360Portlet.setSessionMessage`,
one will see a green banner. I think that the color should depend on `requestStatus`, i.e.
* **green** only for `SUCCESS`
* **red** for `FAILURE`
* **yellow** for everything else 

#### screenshot
![bildschirmfoto-vendors - sw360 - chromium](https://cloud.githubusercontent.com/assets/1187050/11421121/f09b6858-9432-11e5-8956-c5aabf930d19.png)
Banner is green but the message says "Vendor short **could not** be....".

**Comment by heydenreich** [comment]
Postpone to 1.4

**Comment by mcjaeger** [comment]
maybe could be covered if we update to 6.2...GA6 or 7

**Comment by mcjaeger** [comment]
maybe in the BDP Import section - there are red banners, please test.

**Comment by heydenreich** [comment]
This would be possible with acceptable effort:
![liferayuserfeedback](https://cloud.githubusercontent.com/assets/14327740/18163091/90c7a822-7039-11e6-93bd-502731007cd7.png)

A third type of message is difficult and requires a Liferay plugin. Removing the green and the first red message is maybe possible, but not clear with how much effort.

**Comment by heydenreich** [comment]
This is how to hide the standard messages;

SessionMessages.add(request, PortalUtil.getPortletId(request) +
                            SessionMessages.KEY_SUFFIX_HIDE_DEFAULT_ERROR_MESSAGE);
SessionMessages.add(request, PortalUtil.getPortletId(request) +
                            SessionMessages.KEY_SUFFIX_HIDE_DEFAULT_SUCCESS_MESSAGE);

These lines should be placed after 
SessionMessages.add(request, "request_processed",  successMsg); and 
SessionErrors.add(request, "error-key");

**Comment by heydenreich** [comment]
Result:
![image](https://cloud.githubusercontent.com/assets/14327740/18519032/a0ce22c8-7aa2-11e6-8eae-0bd5ee4238e6.png)
