### ISSUE TITLE
Renaming UI Items: Approved -> Report Approved and Project Clearing State

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#491]
There is confusion about some things in the UI:

* the clearing status "Approved" is confusing, because users think it is for the release. In fact it is just that the clearing result (the report) has been approved. Therefore, there should be a rename to "Approved" to "Report Approved" in the UI for clearing status. 

* In Edit view of the project (listing of linked component): Project Mainline State is confusing with mainline state of components / releases. Therefore it should be called "Project Mainline State"

* Rename all occurences of "component mainline state" to "release mainline state"

* Try not to leave an "mainline state" labels open, should be always "release ...", "project ..."

**Comment by maierthomas** [comment]
Currently the column label in clearing status for projects is "Project Mainline State".
Should this be changed to "Project Mainline state"?
