### ISSUE TITLE
Export all project data as a kind of report

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#502]
The Export spreadshet is OK, but not so much human readable. Idea would be to print a (PDF, HTML, text) output of the project with all the data contained: linked items as well as the metadata

Does not need to PDF, could be also HTML or Text key value. Idea is just that current printing looks super odd and there is no meas to have the project data just printed out with linked components and attributes.

**Comment by alexbrdn** [comment]
Someone had this idea of cusomizable export (i.e. where user can select columns to be generated before starting the export) that we've discussed shortly already. Maybe that would do the trick.

**Comment by mcjaeger** [comment]
(from discussion)

let's have a style sheet for printing which allows the user to have the content printed cleanly and also: might work with other dataset types as well
