### ISSUE TITLE
Add different e-mail notifications

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#504]
The user shall be able to have different notifications by e-mail:

* changes on project where own role is {creator, moderator, clearing admin, responsible}
* changes on release
* changes on own moderation requests
* new moderation requests assigned

And there should be an UI where the user could switch on and off these values.

So, ticket would be a simple UI in the Admin section which is then available for the user and then have the additional notifications added.

**Comment by alexbrdn** [comment]
@mcjaeger, should the preferences be set per object type and user role? I.e. should I be able to define that I want notifications for projects where I am the owner, but not on projects where I am moderator?
