### ISSUE TITLE
Error exporting project when no attachment is present

### ISSUE THREAD

**Issue by bodetc** [sw360/sw360portal#509]
When using any of the export buttons in the Project Details -> Linked Releases And Projects, the following error occurs:
<img width="1360" alt="screen shot 2017-07-20 at 12 48 43" src="https://user-images.githubusercontent.com/22469333/28414992-216cd0fc-6d4e-11e7-9044-4b2de46ef3b7.png">
This is due to a NullPointerException in the Portlet which seems to occur when no attachment is present.

**Comment by bodetc** [comment]
I will fix this as part of another ticket.

**Comment by lepokle** [comment]
I think this is fixed.

**Comment by bodetc** [comment]
Yes, this was fixed with the docx pull request
