### ISSUE TITLE
Handle "duplicate" components

### ISSUE THREAD

**Issue by ImfeldC** [sw360/sw360portal#527]
**Problem**: We face an issue with "duplicate" components; either due migration or user mistake; the "same" component was created multiple times. 
As those components (and releases) are already used in projects and have clearing states, etc.; it's not easy to manual clean them up.

**Solution**: 
- Provide possibility to "join" components. Joined components would be "seen" as one component. 
- Provide possibility to "join" releases (of "joined" components). Joined "releases" would be "seen" as one release of a component.

**Details**:
Component/Summary/General tab: Summarize the values (as list) of the "joined" components
Component/Summary/Release Aggregate Data tab: Summarize the values (as list) of the "joined" components
Component/Summary/Roles tab: Summarize the roles of the "joined" components
Component/Release Overview tab: List all releases of "joined" components
Component/Attachments tab: List all attachments of "joined" components
Component/Vulnerabilities tab: List all vulnerabilities of "joined" components

**Comment by ImfeldC** [comment]
Another approach to handle this problem, could be to provide the possibility to mark a component or release as "duplicate" and link them to (master) data set.
In this case the component or release marked as duplicated could no longer be used and edited. 
Manual clean-up would be required to transfer data from (duplicate) data set to (master) data set.

**Comment by maximilianhuber** [comment]
We are already frequently discussing about a "merge" functionality. For example in https://github.com/sw360/sw360portal/issues/278.

**Comment by mcjaeger** [comment]
since it is there https://github.com/sw360/sw360portal/issues/278 please constinue discussion there:
