### ISSUE TITLE
User search does not seem to look for first name - Pt 2

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#535]
Actually, the user search from a user entry field (for moderators, for component owner, etc) does indeed to look for last name only.

* It should looks for first name, last name and e-mail address.
* Moreover, the listing could be improved with sort-a-bility for first name, last name, e-mail and group
* Consider fuzzy search for umlauts
* Limit result entries to 100 (better for blank searches)

**Comment by imaykay** [comment]
Entry point might be `org.eclipse.sw360.portal.portlets.Sw360Portlet.dealWithUserAction(ResourceRequest, ResourceResponse, String)` which finally uses `org.eclipse.sw360.datahandler.db.UserRepository.searchByName(String)`

It might be a good idea to generate a new view on couchdb (or even use lucene) which might probably need a new method in the thrift service.

**Comment by mcjaeger** [comment]
@ChristophNiehoff for the question, if department or role: department! (a.k.a. group)
