### ISSUE TITLE
Cannot edit projects on Firefox

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#543]
On the latest 2.3.0-SNAPSHOT, when trying to edit a project, the Update Project is not working on Firefox. On the Chrome and IE it is working. Tried also with clean cache. The following is displayed in the console:
![edit](https://user-images.githubusercontent.com/19324942/29706796-b8419ee6-898b-11e7-923c-bffd0420b8c6.PNG)

**Comment by imaykay** [comment]
Hi @adrian-evo - did you clean your cache in all three browsers or just firefox?

**Comment by mcjaeger** [comment]
hi, I have seen this too. What I observed:
* error is after clean vagrant deployment
* error is in Firefox, Safari
* it is just the "Update Project" at both locations (upper left, lower left)
* even after complete deletion of browser data
