### ISSUE TITLE
How does LicenseInfo Generation work, and what does the content of result mean?

### ISSUE THREAD

**Issue by datnd** [sw360/sw360portal#554]
hello,

I am working with sw360 and have two questions.  Could you please teach me?
1.  I got SPDX file from fossology and attached to release on sw360., then I tried LicenseInfo Generation and I got result. Data in the result seems like just removing html data in SPDX file, is that right?
2. How can I use the result file? The content of the result file only contain licenses which were not identified by fossology, is that right?

Thank you very much.

**Comment by mcjaeger** [comment]
Hi, thanks for asking this:

1. it is XML data, not HTML? I think yes. For a project with a single release, it is maybe trivial. But the bigger sense comes when generatig the license info aggregated for multiple releases in a project with SPDX attachments into one text, xhtml or docx document..

2. No, not quite? The content is the identified licenses and copyright statement from the tool that created the SPDX document (could be fossology). You can use the result file to provide this as documentation of involved open source software including licenses and copyright statements in your project or product.

**Comment by datnd** [comment]
Thank you for explaining!
