### ISSUE TITLE
License generation shall be clean

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#559]
The license texts contain some times some characters which are confusing in a license documentation output, most prominently, there are HTML escaped characters starting with the ampers and character.

Formatting issues that should be cleaned up before generation:

* eliminate all characters from the source files (SPDX, CLI) which shall not belong in the text
* if the output is text, the HTML escaped characters shall be just written as their text value, for HTML output, according rendering.
* if there are HTML style tags (e.g. for bold typing), they should be ignored in the text output, but rendered in the HTML output.
* if there are HTML formatting tags, they should be rendered for both cases (new line, paragraph, etc)

**Comment by alexbrdn** [comment]
Note that bullet point 2 
> * if the output is text, the HTML escaped characters shall be just written as their text value, for HTML output, according rendering.

is solved by the combination of #586 and #656
