### ISSUE TITLE
Attachements table headers take up multiple lines

### ISSUE THREAD

**Issue by stevinus1** [sw360/sw360portal#569]
Using firefox (1243x1624 resolution), the headers for the attachment table take up multiple lines, which looks messy.
![screenshot from 2017-09-08 09-52-18](https://user-images.githubusercontent.com/30042647/30201597-a46e7056-947b-11e7-9e68-e35e05f69f74.png)

**Comment by ChristophNiehoff** [comment]
I also find the three header lines a bit confusing if there are not attachments.

![screenshot from 2017-09-08 10-11-28](https://user-images.githubusercontent.com/10673021/30202375-87acc87a-947e-11e7-930f-36afa244e3f6.png)

Maybe in the case of no attachments we could show only the first header line saying "Attachments" and immediately below it the "No attachments yet"?    But this is just personal taste...

**Comment by ChristophNiehoff** [comment]
Also, in the firefox (ubuntu, 55.0.2 (64-bit))  the table is not rendered correctly.

![screenshot from 2017-09-08 13-47-06](https://user-images.githubusercontent.com/10673021/30210373-affaf5ea-949c-11e7-9ba0-886601fbda77.png)

@lepokle  Could you have a look at it?

**Comment by lepokle** [comment]
@ChristophNiehoff last picture indicates that you didn't clear the cache

**Comment by lepokle** [comment]
If we prevent the table headers from wrapping, it would enable a horizontal scrolling which is not really nice. So maybe we just reduce the space for the filename a little bit.

Showing less headers if no a attachments are present might be a messy an inconvenient for the user.

**Comment by ChristophNiehoff** [comment]
Oh yes....   That's embarrassing...  I can confirm that it renders well on firefox.
