### ISSUE TITLE
Attachments can't be  added if there is no attachment before

### ISSUE THREAD

**Issue by lepokle** [sw360/sw360portal#578]

**Comment by alexbrdn** [comment]
Just tested adding an attachment to a component and a project that had no attachments before: worked fine. What's the problem?

**Comment by lepokle** [comment]
Previous code will throw a Nullpointer-Exception if `documentAttachments` is null. This was case for uploading attachments to a release in my case.

**Comment by alexbrdn** [comment]
I have just tested with master (54d2106) and still cannot reproduce the problem. Created a new component, then edited it to add an attachment -> attachment saved, no NullPointerExceptions in the log.
It's hard for me to confirm that the problem is fixed if I can't even reproduce the problem.

**Comment by alexbrdn** [comment]
Tested it with a new release as well. No NPE.

**Comment by alexbrdn** [comment]
Got it reproduced by deleting the field `attachments` from a release in the DB.

**Comment by lepokle** [comment]
Strange, no idea how this got null in my instance. Maybe if attachments were deleted? Anyhow, thanks for the quick merge.
