### ISSUE TITLE
License moderation broken

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#582]
When adding a todo or edit white list as user, there is a moderation request message, however none of the admins get the moderation request.

**Comment by ChristophNiehoff** [comment]
It appears that this is an unexpected side effect of pull request #551 . I will have a look at it.

**Comment by ChristophNiehoff** [comment]
The problem seems to be the following:  During the creation of the moderation request `ModerationDatabaseHandler.getAllSW360Users()` is called. This calls in the end `UserSearch.saerchByNameAndEmail(null)`. The `null`-arguments clashes with the newly implemented lucene search.
