### ISSUE TITLE
Vendor edit in release broken

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#583]
Editing a vendor (once set) doe snot work anymore: clicking the text field (which is with grey background) brings:

![grafik](https://user-images.githubusercontent.com/3418977/30434021-60f92286-9966-11e7-80ab-4ce579a6c685.png)

tested with 

https://github.com/sw360/sw360portal/commit/368caa5ad892e08b51e6f3790be5fff324678a21

(230-snapshot, I assume it is in current master as well)

**Comment by lepokle** [comment]
I'm not able to reproduce it on master or fix/598-javascript-error-on-detail-pages

**Comment by lepokle** [comment]
Even not reproducible with FF

**Comment by mcjaeger** [comment]
retested: works now.
