### ISSUE TITLE
Sanity check for external ids present, but not reported to user?

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#590]
While testing https://github.com/sw360/sw360portal/pull/537 I came accross the following:

* log in with "user user"
* open a release with six external ids, not the user's one, so implying a moderation request
* delete all of them, submit moderation with message
* the message says "Moderation has been sent ..."
* then logging in with admin user
* moderation request is not there
* logging in as user user
* deleting 5 of the 6 external ids (at another release)
* logging in as admin user -> moderation request is there

@alexbrdn maybe the sanity check also kicks in for the external ids, but is not reported to the user, or is something wrong with the test data I have used?

**Comment by alexbrdn** [comment]
@mcjaeger, the sanity check PR didn't even touch any classes related to releases. It can only apply to projects. This must be some other problem.

**Comment by alexbrdn** [comment]
I've performed the steps you described and couldn't reproduce the problem. Everything worked as expected for me.

**Comment by mcjaeger** [comment]
testetetetd: works as expected, no issue here.
