### ISSUE TITLE
Generate License Info button not working

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#592]
Tested on master branch, after clean deplyoment and clean cache, both Firefox and Chrome. Once it was working on IE.

The buttons Generate License Info and Source Code Bundle are not working. Export Spreadsheet is working. The error on F12 is attached.

![gen lic info](https://user-images.githubusercontent.com/19324942/30694863-9aeec522-9ede-11e7-8672-65d4e2e849fd.PNG)

**Comment by lepokle** [comment]
PR #599 also fixes this issue
