### ISSUE TITLE
Add attachment does not work in Safari and Firefox

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#594]
When doing a clean deployment of 2356253, the adding of attachments is not working.

Below the screenshot when clicking the referring button.

Attachments for component and project work.

<img width="1607" alt="screen shot 2017-09-22 at 09 37 07" src="https://user-images.githubusercontent.com/3418977/30734048-e1122f08-9f79-11e7-9774-dcdb3dac8819.png">

**Comment by lepokle** [comment]
PR #599 also fixes this issue.
