### ISSUE TITLE
Simplify adding a release to a project

### ISSUE THREAD

**Issue by tngraf** [sw360/sw360portal#613]
Our workflow to add a (new) release to a project is
1. search for a release in the components/releases view
2. vedit the project, search AGAIN for the release and add it

It would be easier the following way (like it was possible in Mainline Portal):
1. search for a release in the components/releases view
2. click on and "Add" button which opens a selection dialog for a project
3. select a project (maybe the dialog also remembers the last project used)
4. click OK to add the release to the selected project.
The user if afterwards still in the components/releases view and can search for the next 
component/release to add.

**Comment by mcjaeger** [comment]
appears to be a duplicate https://github.com/sw360/sw360portal/issues/443

please reopen if I am wrong
