### ISSUE TITLE
Component merge support

### ISSUE THREAD

**Issue by bs-jokri** [sw360/sw360portal#627]
_From @bs-jokri on July 21, 2016 22:44_

As a clearing admin I want to combine two component documents if I see they describe the same component. This can eg happen if i import component information from two data sources

_Copied from original issue: bsinno/sw360#265_

**Comment by bs-jokri** [comment]
_From @maxhbr on May 30, 2017 14:4_

Issue on upstream: https://github.com/sw360/sw360portal/issues/278

**Comment by mcjaeger** [comment]
is actually here https://github.com/sw360/sw360portal/pull/602

**Comment by bs-jokri** [comment]
@bodetc please review PR #602 and check if ok and resolves that ticket.

**Comment by mcjaeger** [comment]
@bs-jokri while I am certainly happy if cedric has a look at this, please let's try to use the task assignments at the pull requests to avoid ovelapping work. Maybe following the current task assignment and also I am kind of remembering the telco on Monday, .... Alex has planned to at these

@alexbrdn  please confirm that you have not started the review in fact. And the next question is actually, when Cedric is actually picking up these, please for us in one week would be too late, as this is a larger PR and we should not afford to have it open for a long time.

**Comment by mcjaeger** [comment]
duplicate of https://github.com/sw360/sw360portal/issues/278

**Comment by bs-jokri** [comment]
ok
