### ISSUE TITLE
Finish PR #414 to support SPDX Tag Value Files

### ISSUE THREAD

**Issue by bs-jokri** [sw360/sw360portal#652]
_From @bs-jokri on June 8, 2017 11:44_

- Use Tag Value Parser from SPDX-Tools
- is to be used with files with ending .spdx

_Copied from original issue: bsinno/sw360#440_

**Comment by bs-jokri** [comment]
_From @maxhbr on June 26, 2017 11:42_

Parser in the spdx-tools: https://github.com/spdx/tools/blob/master/src/org/spdx/tag/HandBuiltParser.java

**Comment by bs-jokri** [comment]
_From @bodetc on September 5, 2017 7:51_

The current implementation of the tool (from spdx tools) does not allow to parse even the example file that is provided. The tool seems to be pretty broken.

**Comment by bs-jokri** [comment]
A possible outcome could also be that SPDX Tools are just not capable fo handling Tag Value files. However, it would be good if we can process them too. If you find some fixes in SPDXTools to make it work, we can consider contributing that to the upstream project.

**Comment by bs-jokri** [comment]
Timeboxed 2d

**Comment by bs-jokri** [comment]
@maxhbr could you please provide some test files generated with FOSSology?

**Comment by bs-jokri** [comment]
to convert to tag value
http://13.57.134.254/app/compare/

**Comment by bodetc** [comment]
Result from my search:
It seems that the example Tag files provided by the SPDX Tools [https://spdx.org/spdx-tagvalue-example](here) and [https://spdx.org/spdx-tagvalue-example](here) are not valid. For instance `DocumentID` is not a valid tag.

However, when you convert the example RDF file to Tag-Value using [http://13.57.134.254/app/convert/](this website) the converter works properly. I also tried some example RDF files provided by Fossology, and they are parsed properly.

The code of the converter seem dodgy in some places, so I cannot certify that it would convert all valid TV files will be parsed without errors.

**Comment by bodetc** [comment]
Look at Fossology generated TV file and the error message in the GUI.

**Comment by bs-jokri** [comment]
ok
