### ISSUE TITLE
Define Lar file for BDP Import Service and remove Portlet from main Lar file of SW360

### ISSUE THREAD

**Issue by bs-jokri** [sw360/sw360portal#653]
_From @bs-jokri on September 25, 2017 7:56_

Two subtasks:

1. Create lar file for only BDP Import Portlet
2. Remove configuration of BDP import Portlet from main SW360 portlet (private)
3. Add extra lar file to configure BDP import portlet
4. store lar file in frontend/configuration
5. Add additional description about how to configure bdp import portlet in documentation.
_Copied from original issue: bsinno/sw360#490_

**Comment by bodetc** [comment]
See https://github.com/bsinno/sw360/pull/495

**Comment by bs-jokri** [comment]
ok
