### ISSUE TITLE
Check what the new entry "Security Vulnerability Monitoring: disabled" means

### ISSUE THREAD

**Issue by bodetc** [sw360/sw360portal#658]
See the PR that introduced the feature: https://github.com/sw360/sw360portal/pull/539

**Comment by bodetc** [comment]
@bs-jokri: As far as I can see from the pull request, this adds a flag "enableSvm" on each project.
The effect of this flag is only the color of the Vulnerability count: It is red only if enabled.

<img width="236" alt="screen shot 2017-10-13 at 17 17 28" src="https://user-images.githubusercontent.com/22469333/31553385-9cdd26c2-b03a-11e7-920f-469e5e846451.png">

**Comment by bs-jokri** [comment]
@bodetc so no further action required from our sidE?

**Comment by bodetc** [comment]
No, this is only a cosmetic change for us.
Let's keep a eye out in case this flag gets used for something else.

**Comment by bs-jokri** [comment]
Ok, but then close for now
