### ISSUE TITLE
Consistent presentation of Releases in Vulnerability portlet

### ISSUE THREAD

**Issue by bodetc** [sw360/sw360portal#667]
In the linked releases of the Vulnerability Portlet, the presentation is not consistent with the rest of the Portal (see screenshot). This should be made consistent: "releaseName (version)"
![image](https://user-images.githubusercontent.com/22469333/31781955-ef5c6b6a-b4f9-11e7-8d0b-fce8f59c1f6e.png)

**Comment by bodetc** [comment]
Done with PR https://github.com/sw360/sw360portal/pull/664

**Comment by bs-jokri** [comment]
ok
