### ISSUE TITLE
Long-Term Fix PortalProperties

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#67]
PortalProperties literally usses 110SNAPSHOT at the moment. This has to be modified to be independent of the release name. 

Otherwise we get problems in the next release...

**Comment by heydenreich** [comment]
This will be fixed as soon as the bsinno repo has contributed to this repo.

**Comment by mcjaeger** [comment]
it is not in the code anymore  is this fixed for now as this was introduced when moving to single portlet and referring commit? (and can the issue be closed?)

**Comment by heydenreich** [comment]
It was broken and hotfixed. When introducing single tomcat this was also solved as a by-product, as since then, portlet names do not contain the version number any more. Another long term-fix will be introduced via the bsinno repo, but the issue can already be closed.
