### ISSUE TITLE
Strange z character displayed on Moderation Change Project

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#672]
Noticed on latest master. The lower case z char is displayed on moderation page at the end of project name.

![capture](https://user-images.githubusercontent.com/19324942/32218573-fc56f842-be33-11e7-87fd-bc85f7f01f35.PNG)

**Comment by mcjaeger** [comment]
does not seem to be always there ... tested on productive and not found

**Comment by adrian-evo** [comment]
Tested on latest master, still reproducible in my case.

![proj z](https://user-images.githubusercontent.com/19324942/33544420-58083c68-d8e3-11e7-861f-ea34cf59476b.PNG)
