### ISSUE TITLE
Merge functionality not working

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#701]
Tried merge functionality and in my case it is not working on latest master. Tried with clean deployment. In the attached screnshots you can see the errors captured on Chrome and Firefox.

![merge](https://user-images.githubusercontent.com/19324942/33941222-72fa4fdc-e01a-11e7-89a8-a3660bd4a26c.PNG)

![merge chrome](https://user-images.githubusercontent.com/19324942/33941226-764eee72-e01a-11e7-9285-79847df11a45.PNG)

**Comment by maxhbr** [comment]
Minifier again? Are their comments (especially `//....`) in the corresponding code?

**Comment by mcjaeger** [comment]
on another deployment it works for Adrian and me.
