### ISSUE TITLE
Link between projects and components/releases is missing in the REST API

### ISSUE THREAD

**Issue by deveaud-m** [sw360/sw360portal#718]
The links between projects and components or component's releases is not reflected in the REST API right now.
In the `projects` endpoint, only contains embedded resources like `createdBy` and `moderators` but doesn't contain any information regarding available project releases and link component's releases.

This is a crucial functionality to be able to automatically list components, and contained information, to product releases. I'm not sure if this gap is due to an incomplete  API specification or the generation of the API itself.

**Comment by bs-jokri** [comment]
PR #712 adds this functionality.

**Comment by deveaud-m** [comment]
@bs-jokri Thanks for the info!

**Comment by maierthomas** [comment]
We should reopen the issue because the PR #712 contains only a new endpoint (GET /projects/{projectId}/Releases) which shows all the releases for a specific project.

The problem is the linked release relationship between a project and a release.
The REST API shows only linked releases with relation `CONTAINED`.
All linked releases should be visible in the REST API independent of their release relationship.

**Comment by bs-jokri** [comment]
You are right. However, we have to think about how to communicate the relation type. Maybe directly in the embedded resource.

**Comment by maierthomas** [comment]
What about "wrapping" the link and add all relevant information to `linkRelation`.
`linkRelation `is set if its necessary and it contains the specific data fields for the link.

e.g.

>  "containedReleases": [
>       {
>         "name": "Apache Xerces C++",
>         "version": "3.1.3",
>         "clearingState": "APPROVED",
>         "_links": {
>           "self": {
>             "href": "https://localhost:8443/resource/api/releases/065f3aa45c6683297fd1bb39290edbe0",
>             "linkRelation": {
>               "releaseRelation": "CONTAINED",
>               "mainlineState": "OPEN"
>             }
>           }
>         }
>       }
>     ],
