### ISSUE TITLE
Add clearing state to dropdown menu of releases at the detailRelase view

### ISSUE THREAD

**Issue by LinusschTU** [sw360/sw360portal#738]
It would be useful for the user if he could see in the dropdown of the detailRelease view if the releases are already cleared. Maybe add a green dot behind a release if it's cleared and a red dot when not.

![image](https://user-images.githubusercontent.com/3418977/35805668-0bd858ac-0a7d-11e8-918b-ae7b3949176c.png)

**Comment by LinusschTU** [comment]
I worked on a possible solution. What do you think of the design?
![sw360bild](https://user-images.githubusercontent.com/35561003/36383381-43cf21ae-158c-11e8-9216-feef7179a616.jpg)

**Comment by alexbrdn** [comment]
Nice, but I would move the dot closer to the text, or the user could miss it entirely.

Also, there's already a set of colors for red/yellow/green in sw360.css. The colors you chose look somewhat darker. I'd rather you stick to the available colors, unless you have a good reason to deviate.

**Comment by LinusschTU** [comment]
Here is a second Version. We have five clearing states: new clearing, sent to fossology, under clearing,  report available and approved. At the moment I show new clearing and sent to fossology as a red dot, under clearing and report available as a yellow dot and approved as a green dot.

![sw360_dropdown_v2](https://user-images.githubusercontent.com/35561003/36470120-1a289b50-16ea-11e8-847b-45689a72b9d6.png)

**Comment by alexbrdn** [comment]
way better, IMO
