### ISSUE TITLE
Access token credentials for dev/stage/productive system

### ISSUE THREAD

**Issue by tngraf** [sw360/sw360portal#793]
Currently we have different passwords to get the access token for the different servers.

**Question 1:** do we really need different passwords or is one signe password sufficient?

**Question 2:** Does the password need to be secret ro can we have it in the source code
stored at code.siemens.com?

**Question 3:** Is this really the best way to get an access token? When we would use a mechanism
similar to Oauth2, user woud use the UI to get a personal token. This token can then get used
to get an access token (which is the valid only for a short time period)...

**Comment by mcjaeger** [comment]
please do not open opration issues on the public github.com
