### ISSUE TITLE
Self registration portlet

### ISSUE THREAD

**Issue by stefanjaeger-evo** [sw360/sw360portal#80]
- a new frontend portlet should be implemented which allows user to register by their self
- the portlet have to be accessible anonymously
- all required user properties (see user csv) including group and role (dropdown) should be entered
- the portlet should register the user in liferay AND create the user for the backend
- reusing the code of the user csv import is self-evident (maybe refactoring is required)
- the user should be deactivated in liferay so that a login is not possible
- a moderation request should be created (for whom?)
- after the moderation request is accepted, the user will be activated
- if the moderation request is declined the user will be deleted in the backend AND in liferay

**Comment by mcjaeger** [comment]
1+

so, the user self reg could be on the page when the user surf to liferay and not logged in ...
