### ISSUE TITLE
Can't generate Xhtml (SW360 generate) from big SPDX files (FOSSology generate).

### ISSUE THREAD

**Issue by binhth1307** [sw360/sw360portal#807]
Hi all,

My FOSSology generated SPDX file of gcc-4.8.4-1.tar package. Size of this SPDX file is about: 228453 KB. I uploaded this SPDX file to SW360 software. Then i can't generate catalog file (Xhtml file in SW360 software). This is repeated with gcc-4.9.2-10.tar package (121170 KB), e2fsprogs-1.42.12-2.tar package (219655 KB) and glibc-2.19-18+deb8u10.tar package (21111 KB). Is it a bug of database of couchDB?

Thanks and Best Regards,
BinhTH

**Comment by alexbrdn** [comment]
This is way too little information to be able to answer you. You'll have to research the problem and provide more details. (What's the observed behavior? What errors are there in the log? etc.)

**Comment by binhth1307** [comment]
Hi alexbrdn,

Thanks for your attention. This error is not generate Xhtml file (from big SPDX file of FOSSology). Whatever I generate Xhtml file (from big SPDX file of FOSSology), my server is lagged, didn't accessed to SW360 web.

Thanks and Best Regards,
BinhTH

**Comment by alexbrdn** [comment]
I don't know how to help you with this little information. I can only guess that your server can't cope with the size of the files you throw at it. _If_ that's the case, maybe you should get a more powerful server. Or, again, provide more information about the issue and explain why you think this is a problem with sw360 itself.

**Comment by binhth1307** [comment]
Thank alexbrdn very much. I detected log when the tomcat was running as below:
![image](https://user-images.githubusercontent.com/34565625/38416738-ec868600-39bf-11e8-8640-b2147481d026.png)

**Comment by alexbrdn** [comment]
Well, in this case, I don't see it as a problem of the sw360 software. I don't think we're going to create a streaming implementation of spdx tools to try and cope with files that big. It would be way out of scope for our project.
