### ISSUE TITLE
Adding predefined categories to type (of component): DOAP

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#82]
In some earlier  version there was a pull down menue, like as with programming languages for the component types.

So the user did not have free form, but a list to select from.

That should be back again. And is should based on an already established standard:

https://projects-old.apache.org/categories.html

(adding "other" mght be useful as well)

If could be implemented the same way it is done with platforms or programming languages.

**Comment by AngelM1981** [comment]
What about simple executables. They should be added too.

**Comment by heydenreich** [comment]
The website seems to be down. Let's try again tomorrow, but otherwise: Could you also provide the list?

**Comment by AngelM1981** [comment]
We can try to build a list:

Here are my proposals for the list:

- Executable
- Static library
- Dynamic library
- Webservice

**Comment by mcjaeger** [comment]
I wondered if the DOAP categories are used within the Apache project search:

https://projects.apache.org/projects.html?category

Useful from Apache Categories:

Framework (1):
Library (3):
SDK (2):
big-data (32):
build-management (20):
cloud (11):
content (17):
database (25):
graphics (5):
http (15):
javaee (10):
library (92):
mail (2):
mobile (1):
security (3):
testing (5):
virtual-machine (1):
web-framework (27):
xml (31):

Not So useful from Apache Categories

ftp (1):
osgi (6):
regexp (2):
retired (19):
hadoop (2):
httpd-module (4):
identity-management (3):
identity-provisioning (2):
network-client (24):
network-server (39):
composite-oriented-programming (1):
Kerberos (1):
OSGi (1):

**Comment by alex-evo** [comment]
So what's the definitive list of categories we're going to suggest? The link from the original issue text is down. The DOAP RDF does not suggest a list.

BTW, I would consider osgi, network-client, and network-server useful categories.

**Comment by mcjaeger** [comment]
I think the most important issue that this list is configurable. As for the list I propose to have the "Useful from Apache Categories:" with the additions you have mentioned.

**Comment by AngelM1981** [comment]
I fully agree. The field should be editable and autocompletion with already used values should be possible.
