### ISSUE TITLE
Typo in csv export for components

### ISSUE THREAD

**Issue by bs-jumar** [sw360/sw360portal#824]
There is a typo in the exported .csv for the components.

Typo:
**Repostitory -> Repository**

Typo and its references can be found in [ComponentCSVRecord.java](https://github.com/sw360/sw360portal/blob/58b10f4ac310352b27569712e11e78f4ba056a25/libraries/importers/component-importer/src/main/java/org/eclipse/sw360/importer/ComponentCSVRecord.java), [ComponentCSVRecordBuilder.java](https://github.com/sw360/sw360portal/blob/58b10f4ac310352b27569712e11e78f4ba056a25/libraries/importers/component-importer/src/main/java/org/eclipse/sw360/importer/ComponentCSVRecordBuilder.java) and [test-components.csv](https://github.com/sw360/sw360portal/blob/c6f69420e11df11d5ff341109da234cdabf06efa/libraries/importers/component-importer/src/test/resources/org/eclipse/sw360/importer/test-components.csv)

**Comment by bs-jokri** [comment]
Hi @bs-jumar, thanks for pointing this out. However, we moved our issue tracker to eclipse recently. Could you please move your issue here 
https://github.com/eclipse/sw360/issues
and close this one. Thanks

**Comment by bs-jumar** [comment]
Issue moved https://github.com/eclipse/sw360/issues/273
