### ISSUE TITLE
Component Search

### ISSUE THREAD

**Issue by timowolf** [sw360/sw360portal#827]
When selecting a linked release I am using the search. But when searching for a component name like `foo-bar-tso` all components that contain foo, bar and tso are listed. Not those that only contain foo-bar-tso in the name.

**Comment by alexbrdn** [comment]
@timowolf, the sw360 repository has been moved to https://github.com/eclipse/sw360
We almost completele overlooked your issue. Please excuse the misunderstanding. We are going to archive this repository in the near future.

Kindly re-open your issue at the new repository. Thanks.
