### ISSUE TITLE
Adding travis-CI support / file for sw360

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#84]
travis should be pulled in so we have regular builds and also test runs on the commits. technicaly, this ticket is about providing the according  travis file.

Let's start simple: just the usual build and test.

I am not sure about usual, because our testing involves couchdb. Maybe we skip couchdb tests for the first (and fork this to another ticket). Or download and start could be feasible?

**Comment by maximilianhuber** [comment]
Once someone with permissions (@mcjaeger) has enabled travis-Ci support on https://travis-ci.org/profile/siemens and #132 is merged we will have travis support.

With this changes, travis will setup a trusty with couchdb and thrift and call `mvn install`. This runs all tests.

--

works on my fork, i.e.
![tmp](https://cloud.githubusercontent.com/assets/1187050/13883601/770acd3e-ed2a-11e5-811b-95beec890fb2.png)
