### ISSUE TITLE
links in task assignments portlet

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#93]
Similar to MyComponents and MyProjects, the moderation requests in the MyTaskAssigments Portlet should be linked with the corresponding moderation request (or at least the list).

**Comment by mcjaeger** [comment]
And two things, also consider:
* MyTaskSubmission
* also provide links when moderation was closed (currently goes to red in larger list)

**Comment by alex-evo** [comment]
At the moment, there's no UI where a user can review his moderation requests. What sense does it make to provide links in MyTaskSubmission and where should they point to?

**Comment by alex-evo** [comment]
Never mind. I made a read-only version of the moderation request edit page.
