### ISSUE TITLE
possibility to modify user settings

### ISSUE THREAD

**Issue by heydenreich** [sw360/sw360portal#99]
user wants  to modify settings such as
given name
last name
wantsMailNotification
....

**Comment by mcjaeger** [comment]
shouid be 
a) using the "my accounts" in the liferay upper right user menu
b) using the users portlet in the sw360 admin section (and to be done by the admin)

**Comment by mcjaeger** [comment]
main user attributes are provided by the liferay portal, the last thing with the mails was done here:

https://github.com/sw360/sw360portal/pull/547
